import { EXAM_SLOTS, QUESTION_BLUEPRINTS } from './nmt-knowledge.js';

export const QUESTION_ENGINE_VERSION = 5;
const LETTERS = ['А','Б','В','Г','Д'];
const LABELS = {
  numbers:'Числа та дроби', percents:'Відсотки та пропорції', powers_roots:'Степені та корені', logarithms:'Логарифми',
  equations:'Рівняння', inequalities:'Нерівності', systems:'Системи рівнянь', functions:'Функції та графіки',
  progressions:'Прогресії', trigonometry:'Тригонометрія', calculus:'Похідна та інтеграл', probability_stats:'Ймовірність і статистика',
  planimetry:'Планіметрія', stereometry:'Стереометрія', word_problems:'Текстові задачі', mixed:'Змішані завдання НМТ'
};
const BLUEPRINTS = new Map(QUESTION_BLUEPRINTS.map(x => [x.id, x]));

const randInt=(a,b)=>Math.floor(Math.random()*(b-a+1))+a;
const pick=(a)=>a[randInt(0,a.length-1)];
function shuffle(arr){const a=[...arr];for(let i=a.length-1;i>0;i--){const j=randInt(0,i);[a[i],a[j]]=[a[j],a[i]];}return a;}
const gcd=(a,b)=>b?gcd(b,a%b):Math.abs(a);
const ua=(n)=>Number.isInteger(Number(n))?String(Number(n)):String(Number(n).toFixed(6)).replace(/0+$/,'').replace(/\.$/,'').replace('.',',');
const math=(s)=>`\\(${s}\\)`;
function frac(n,d){const g=gcd(n,d);n/=g;d/=g;if(d<0){n=-n;d=-d;}return d===1?math(String(n)):math(`\\frac{${n}}{${d}}`);}
function unique(items){return [...new Set(items.map(String))];}
function topicLabel(topic){return LABELS[topic]||topic;}
function metadata(id){const b=BLUEPRINTS.get(id)||{};return { blueprint_id:id, subtopic:b.subtopic||null, skill:b.skill||null, source_confidence:b.source_confidence||2, engine_version:QUESTION_ENGINE_VERSION };}
function makeChoice(id,{topic,question,correct,distractors,explanation,diagram_svg=null,difficulty='середній'}){
  let opts=unique([correct,...distractors]); let guard=0;
  while(opts.length<5&&guard++<30) opts=unique([...opts,ua(randInt(-30,80))]);
  opts=shuffle(opts.slice(0,5)); const ci=opts.indexOf(String(correct)); if(ci<0) throw new Error('correct option lost');
  return {type:'choice',topic,topic_label:topicLabel(topic),difficulty,question,options:opts,correct_index:ci,explanation,max_score:1,diagram_svg,...metadata(id)};
}
function makeMatching(id,{topic,question,left,options,correct_pairs,explanation,diagram_svg=null}){
  return {type:'matching',topic,topic_label:topicLabel(topic),question,left,match_options:options.map((label,i)=>({code:LETTERS[i],label:String(label)})),correct_pairs,explanation,max_score:3,diagram_svg,...metadata(id)};
}
function makeShort(id,{topic,question,correct_value,explanation,diagram_svg=null,answer_hint='Введи число'}){
  return {type:'short',topic,topic_label:topicLabel(topic),question,correct_value:Number(correct_value),correct_display:ua(correct_value),explanation,max_score:2,diagram_svg,answer_hint,...metadata(id)};
}

function shellSvg(inner, aria='Математична схема'){return `<svg viewBox="0 0 360 230" role="img" aria-label="${aria}" xmlns="http://www.w3.org/2000/svg"><defs><style>.g{stroke:#25272b;stroke-width:2.7;fill:none;stroke-linecap:round;stroke-linejoin:round}.d{stroke:#8c8170;stroke-width:2;fill:none;stroke-dasharray:6 6}.a{stroke:#b58a3c;stroke-width:2.4;fill:none}.t{font:700 16px -apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;fill:#25272b}.m{font:600 13px -apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;fill:#66645f}.grid{stroke:#e4dfd4;stroke-width:1}</style></defs>${inner}</svg>`;}
function barChartSvg(values,labels){const max=Math.max(...values);const bars=values.map((v,i)=>{const h=125*v/max,x=48+i*57,y=176-h;return `<rect x="${x}" y="${y}" width="30" height="${h}" rx="5" fill="#c8a35c"/><text class="m" x="${x+15}" y="${y-8}" text-anchor="middle">${v}</text><text class="m" x="${x+15}" y="198" text-anchor="middle">${labels[i]}</text>`}).join('');return shellSvg(`<path class="g" d="M34 176H326 M34 38V176"/>${bars}`,'Стовпчаста діаграма');}
function trapezoidAngleSvg(angle){return shellSvg(`<path class="g" d="M58 176 L302 176 L250 65 L108 65 Z"/><text class="t" x="42" y="197">A</text><text class="t" x="305" y="197">D</text><text class="t" x="94" y="58">B</text><text class="t" x="252" y="58">C</text><path class="a" d="M270 176 A34 34 0 0 0 287 145"/><text class="m" x="256" y="145">${angle}°</text>`,'Рівнобічна трапеція');}
function parabolaShiftSvg(shift){const pts=[];for(let x=-3;x<=3;x+=.2){const px=180+x*42,py=60+(x-shift)*(x-shift)*13;pts.push(`${px.toFixed(1)},${Math.min(192,py).toFixed(1)}`)}return shellSvg(`<path class="grid" d="M30 115H330 M180 25V205"/><path class="g" d="M30 115H330 M180 25V205"/><polyline points="${pts.join(' ')}" fill="none" stroke="#b58a3c" stroke-width="3"/><text class="m" x="318" y="108">x</text><text class="m" x="187" y="36">y</text>`,'Графік функції');}
function circleRectSvg(r){return shellSvg(`<rect class="g" x="72" y="48" width="216" height="136"/><circle class="a" cx="140" cy="116" r="${r}"/><path class="d" d="M140 116 L72 184 M140 116 L72 48"/><text class="t" x="58" y="202">A</text><text class="t" x="292" y="202">D</text><text class="t" x="292" y="42">C</text><text class="t" x="58" y="42">B</text><text class="t" x="147" y="112">O</text>`,'Прямокутник і коло');}
function triangleMatchSvg(a,b){const h=Math.sqrt(Math.max(1,a*a-(b/2)*(b/2)));return shellSvg(`<path class="g" d="M60 178 L300 178 L180 ${Math.max(40,178-h*7)} Z"/><path class="d" d="M180 ${Math.max(40,178-h*7)} L180 178"/><text class="t" x="44" y="198">A</text><text class="t" x="303" y="198">B</text><text class="t" x="175" y="${Math.max(30,165-h*7)}">C</text><text class="m" x="170" y="203">${b}</text><text class="m" x="95" y="110">${a}</text><text class="m" x="246" y="110">${a}</text>`,'Рівнобедрений трикутник');}
function linkedSolidsSvg(){return shellSvg(`<ellipse class="g" cx="92" cy="164" rx="58" ry="19"/><ellipse class="g" cx="92" cy="66" rx="58" ry="19"/><path class="g" d="M34 66V164 M150 66V164"/><path class="g" d="M205 176 L326 176 L266 54 Z"/><path class="d" d="M266 54 L266 176"/><text class="m" x="55" y="218">циліндр</text><text class="m" x="235" y="218">піраміда</text>`,'Циліндр і піраміда');}

function dataChart(){const vals=[randInt(4,8),randInt(8,13),randInt(10,16),randInt(5,11)];const total=vals.reduce((a,b)=>a+b,0);return makeChoice('data_chart_reading',{topic:'probability_stats',question:'На діаграмі показано кількість учасників у чотирьох групах. Визначте загальну кількість учасників.',correct:ua(total),distractors:[ua(total-vals[0]),ua(total+vals[0]),ua(Math.max(...vals)),ua(vals[1]+vals[2])],explanation:`Додаємо значення всіх чотирьох стовпчиків: ${vals.join(' + ')} = ${total}.`,diagram_svg:barChartSvg(vals,['I','II','III','IV']),difficulty:'легкий'});}
function appliedPercent(){const base=pick([120,160,200,240,300,360,400,500]);const p=pick([20,25,30,40,60]);const part=base*p/100;const askRemain=Math.random()<.5;const correct=askRemain?base-part:part;return makeChoice('applied_ratio_percent',{topic:'percents',question:askRemain?`Із суми ${base} грн витратили ${p}%. Скільки гривень залишилося?`:`Скільки становить ${p}% від ${base}?`,correct:ua(correct),distractors:[ua(part),ua(base-correct),ua(base*p/10),ua(correct+base/10)],explanation:`${p}% від ${base} дорівнює ${part}. ${askRemain?`Залишок: ${base} − ${part} = ${correct}.`:`Отже, відповідь ${correct}.`}`,difficulty:'легкий'});}
function planAngle(){const c=pick([100,110,120,130,140]);const a=180-c;return makeChoice('planimetry_angle_parallel',{topic:'planimetry',question:`На рисунку зображено рівнобічну трапецію ABCD. Визначте кут BAD, якщо ∠BCD = ${c}°.` ,correct:`${a}°`,distractors:[`${c}°`,`${180-a/2}°`,`${a/2}°`,`${90-a/2}°`],explanation:`У рівнобічній трапеції кути при одній основі рівні, а прилеглі до бічної сторони кути в сумі дають 180°. Тому ∠BAD = 180° − ${c}° = ${a}° .`,diagram_svg:trapezoidAngleSvg(c),difficulty:'легкий'});}
function linearIneq(){const a=pick([2,3,4,5]);const bound=pick([3,4,5,6]);const b=pick([1,2,3,5,7]);const rhs=a*bound+b;const candidates=shuffle([bound-2,bound-1,bound,bound+1,bound+2]);const correct=Math.min(...candidates.filter(x=>a*x+b>rhs));return makeChoice('linear_inequality_pick',{topic:'inequalities',question:`Позначте з наведених найменше число, яке є розв’язком нерівності ${math(`${a}x+${b}>${rhs}`)}.`,correct:ua(correct),distractors:candidates.filter(x=>x!==correct).map(ua),explanation:`${math(`${a}x>${rhs-b}`)}, отже ${math(`x>${bound}`)}. Найменше із запропонованих чисел, що більше за ${bound}, — ${correct}.`,difficulty:'легкий'});}
function solidConcept(){const variant=Math.random()<.5;return variant?makeChoice('solid_geometry_concept',{topic:'stereometry',question:'Кулю утворюють обертанням…',correct:'круга навколо його діаметра',distractors:['кола навколо його дотичної','круга навколо хорди, що не є діаметром','прямокутника навколо сторони','трикутника навколо висоти'],explanation:'Куля як просторове тіло утворюється обертанням круга навколо його діаметра.',difficulty:'легкий'}):makeChoice('solid_geometry_concept',{topic:'stereometry',question:'Скільки площин, паралельних площині основи піраміди, можна провести через вершину, що не належить основі?',correct:'лише одну',distractors:['жодної','лише дві','лише три','нескінченно багато'],explanation:'Через точку поза даною площиною можна провести рівно одну площину, паралельну даній.',difficulty:'середній'});}
function functionShift(){const shift=pick([-3,-2,2,3]);const correct=shift>0?`y=f(x-${shift})`:`y=f(x+${Math.abs(shift)})`;return makeChoice('function_graph_transform',{topic:'functions',question:`Графік функції ${math('y=f(x)')} перенесли вздовж осі x на ${Math.abs(shift)} одиниці ${shift>0?'вправо':'вліво'}. Яку функцію отримали?`,correct:math(correct),distractors:[math(`y=f(x${shift>0?'+':'-'}${Math.abs(shift)})`),math(`y=f(x)+${Math.abs(shift)}`),math(`y=f(x)-${Math.abs(shift)}`),math(`y=${Math.abs(shift)}f(x)`) ],explanation:`Горизонтальний зсув на ${Math.abs(shift)} вправо відповідає заміні x на x−${Math.abs(shift)}, а вліво — на x+${Math.abs(shift)}.`,diagram_svg:parabolaShiftSvg(shift>0?1:-1),difficulty:'середній'});}
function probabilityBasic(){const nature=randInt(5,9), buildings=randInt(4,8), people=randInt(3,6);const total=nature+buildings+people;const fav=nature+buildings;return makeChoice('probability_counting_basic',{topic:'probability_stats',question:`Є ${total} світлин: ${nature} із природою, ${people} із людьми та ${buildings} із будівлями. Яка ймовірність навмання вибрати світлину з природою або будівлею?`,correct:frac(fav,total),distractors:[frac(nature,total),frac(buildings,total),frac(people,total),frac(fav,total-people)],explanation:`Сприятливих результатів ${nature}+${buildings}=${fav}, усього ${total}. Ймовірність дорівнює ${fav}/${total}.`,difficulty:'легкий'});}
function vectors3d(){const a=[randInt(-3,3),randInt(-3,3),randInt(-2,2)];const b=[randInt(-3,4),randInt(-3,4),randInt(-2,3)];const c=a.map((v,i)=>v+b[i]);const mag2=c.reduce((s,v)=>s+v*v,0);return makeChoice('vectors_3d',{topic:'stereometry',question:`Задано вектори ${math(`\\vec a=(${a.join(';')})`)} і ${math(`\\vec b=(${b.join(';')})`)}. Визначте квадрат модуля вектора ${math('\\vec c=\\vec a+\\vec b')}.`,correct:ua(mag2),distractors:[ua(mag2+1),ua(Math.abs(c[0])+Math.abs(c[1])+Math.abs(c[2])),ua(a.reduce((s,v)=>s+v*v,0)),ua(b.reduce((s,v)=>s+v*v,0))],explanation:`${math(`\\vec c=(${c.join(';')})`)}. Тому ${math(`|\\vec c|^2=${c.map(v=>`${v}^2`).join('+')}=${mag2}`)}.`,difficulty:'середній'});}
function algebraSimplify(){const k=pick([3,4,5,6]);const m=pick([2,3,5]);const correct=`${k}x+${m*m}`;return makeChoice('algebra_simplify',{topic:'numbers',question:`Спростіть вираз ${math(`${k}x-(x-${m})(x+${m})+x^2`)}.`,correct:math(correct),distractors:[math(`${k}x-${m*m}`),math(`${k*m}x+${m*m}`),math(`${k*m}x-${m*m}`),math(`${k}x-x^2`) ],explanation:`${math(`(x-${m})(x+${m})=x^2-${m*m}`)}. Після розкриття дужок ${math(`${k}x-x^2+${m*m}+x^2=${k}x+${m*m}`)}.`,difficulty:'середній'});}
function geometryStatements(){return makeChoice('geometry_statements',{topic:'planimetry',question:'Які з наведених тверджень правильні? І. Діаметр є найбільшою хордою кола. ІІ. Рівні хорди стягують рівні дуги. ІІІ. Будь-яка хорда більша за радіус.',correct:'лише І та ІІ',distractors:['лише І','лише ІІ','лише ІІІ','І, ІІ та ІІІ'],explanation:'І та ІІ — властивості кола. ІІІ хибне: хорда може бути меншою за радіус.',difficulty:'середній'});}
function logEquation(){const base=pick([2,3,5]);const power=pick([2,3]);const root=Math.pow(base,power);const intervals=[[0,root-1],[root-1,root],[root,root+2],[root+2,root+8],[root+8,root+20]];return makeChoice('log_exp_equation_interval',{topic:'logarithms',question:`Якому проміжку належить корінь рівняння ${math(`\\log_{${base}}x=${power}`)}?`,correct:`[${root}; ${root+2})`,distractors:[`(0; ${root-1}]`,`[${root-1}; ${root})`,`[${root+2}; ${root+8})`,`[${root+8}; ${root+20})`],explanation:`Із ${math(`\\log_{${base}}x=${power}`)} маємо ${math(`x=${base}^{${power}}=${root}`)}.`,difficulty:'середній'});}
function calculusBasic(){const a=pick([2,3,4,5]), b=pick([-4,-2,2,4]);const x0=pick([-2,-1,1,2]);const val=2*a*x0+b;return makeChoice('calculus_basic',{topic:'calculus',question:`Обчисліть значення похідної функції ${math(`f(x)=${a}x^2${b>=0?'+':''}${b}x+1`)} у точці ${math(`x_0=${x0}`)}.`,correct:ua(val),distractors:[ua(val+2*a),ua(a*x0+b),ua(2*a+b),ua(val-b)],explanation:`${math(`f'(x)=${2*a}x${b>=0?'+':''}${b}`)}. Підставляємо ${math(`x=${x0}`)} і отримуємо ${val}.`,difficulty:'середній'});}
function circleRect(){const r=pick([6,8,10,12]);const od=2*r;const correct=math(`${r}(1+\\sqrt3)`);return makeChoice('circle_rectangle_geometry',{topic:'planimetry',question:`У прямокутнику ABCD коло з центром O дотикається сторін AB і AD. Відомо, що ${math(`OD=${od}`)} та ${math('\\angle ADO=30^\\circ')}. Знайдіть довжину AD.`,correct,distractors:[math(`${r}\\sqrt3`),math(`${2*r}`),math(`${r}(2+\\sqrt3)`),math(`${2*r}\\sqrt3`)],explanation:`У прямокутному трикутнику, утвореному радіусом до AD та відрізком OD, ${math(`OD=${od}`)} є гіпотенузою, тому радіус ${math(`r=${r}`)}. Із ${math('\\tan30^\\circ=r/(AD-r)')} маємо ${math(`AD-r=${r}\\sqrt3`)}, отже ${math(`AD=${r}(1+\\sqrt3)`)}.`,diagram_svg:circleRectSvg(58),difficulty:'складний'});}
function trigExact(){const variants=[{q:math('2\\sin(-\\pi/2)+\\cos(3\\pi)'),c:'-3',d:['-2','-1','2','3']},{q:math('\\sin(\\pi/6)+\\cos(\\pi/3)'),c:'1',d:['0','1/2','√2','2']},{q:math('2\\cos(0)-\\sin(\\pi/2)'),c:'1',d:['-1','0','2','3']}];const v=pick(variants);return makeChoice('trig_exact_values',{topic:'trigonometry',question:`Обчисліть ${v.q}.`,correct:v.c,distractors:v.d,explanation:'Використовуємо табличні точні значення синуса й косинуса та акуратно враховуємо знак.',difficulty:'середній'});}
function quadraticChoice(){const r1=randInt(-5,-1),r2=randInt(1,6);const sum=r1+r2,prod=r1*r2;const b=-sum,c=prod;const answer=r2-r1;return makeChoice('quadratic_equation',{topic:'equations',question:`Корені рівняння ${math(`x^2${b>=0?'+':''}${b}x${c>=0?'+':''}${c}=0`)} дорівнюють ${math('x_1,x_2')}, де ${math('x_2>x_1')}. Знайдіть ${math('x_2-x_1')}.`,correct:ua(answer),distractors:[ua(Math.abs(sum)),ua(Math.abs(prod)),ua(answer+1),ua(answer-1)],explanation:`Рівняння має корені ${r1} і ${r2}. Тому ${math(`x_2-x_1=${r2}-(${r1})=${answer}`)}.`,difficulty:'середній'});}
function systemLinear(){const x=randInt(1,6),y=randInt(1,7);const s=x+y,d=x-y;return makeChoice('systems_linear',{topic:'systems',question:`Розв’яжіть систему ${math(`\\begin{cases}x+y=${s}\\\\x-y=${d}\\end{cases}`)}. Знайдіть ${math('2x+y')}.`,correct:ua(2*x+y),distractors:[ua(x+y),ua(2*y+x),ua(x-y),ua(x*y)],explanation:`Додаємо рівняння: ${math(`2x=${s+d}`)}, тому x=${x}, y=${y}. Отже 2x+y=${2*x+y}.`,difficulty:'середній'});}
function progression(){const a1=randInt(2,8),d=randInt(2,6),n=randInt(5,10);const an=a1+(n-1)*d;const sum=n*(a1+an)/2;return makeChoice('progression_ap',{topic:'progressions',question:`В арифметичній прогресії ${math(`a_1=${a1}`)}, ${math(`d=${d}`)}. Знайдіть ${math(`S_{${n}}`)}.`,correct:ua(sum),distractors:[ua(an),ua(sum+d),ua(n*(a1+d)),ua(sum-n)],explanation:`${math(`a_${n}=${a1}+(${n}-1)\\cdot${d}=${an}`)}. Тоді ${math(`S_${n}=\\frac{${n}(${a1}+${an})}{2}=${sum}`)}.`,difficulty:'середній'});}
function powersRoots(){const a=pick([2,3,5]);const n=pick([2,3,4]);const result=Math.pow(a,n);return makeChoice('powers_roots_transform',{topic:'powers_roots',question:`Обчисліть ${math(`\\sqrt{${result*result}}`)}.`,correct:ua(result),distractors:[ua(result*result),ua(a*n),ua(result/a),ua(result+a)],explanation:`Арифметичний квадратний корінь із ${result*result} дорівнює ${result}.`,difficulty:'легкий'});}
function advancedChoice(){return Math.random()<.5?systemLinear():quadraticChoice();}

function matchingFunctions(){const m=pick([2,3]);const left=[math(`y=${m}x`),math(`y=${m}x+2`),math(`y=-${m}x+4`)];const options=['проходить через початок координат','має додатний кутовий коефіцієнт і не проходить через початок','має від’ємний кутовий коефіцієнт','є горизонтальною прямою','не перетинає вісь y'];return makeMatching('matching_functions',{topic:'functions',question:'До кожної функції (1–3) доберіть її властивість (А–Д).',left,options,correct_pairs:{'0':'А','1':'Б','2':'В'},explanation:'Для прямої y=kx+b знак k визначає нахил, а b — перетин з віссю y.'});}
function matchingExpressions(){const vals=[1,4,9];const left=[math('2^0'),math('2^2'),math('3^2')];const options=['(−∞;0]','(0;2]','(2;5]','(5;8]','(8;+∞)'];return makeMatching('matching_expressions',{topic:'powers_roots',question:'Узгодьте вираз (1–3) з проміжком (А–Д), якому належить його значення.',left,options,correct_pairs:{'0':'Б','1':'В','2':'Д'},explanation:`Значення виразів: ${vals.join(', ')}. Далі визначаємо відповідні проміжки.`});}
function matchingPlanimetry(){const cfg=pick([{side:5,base:6,h:4},{side:10,base:12,h:8},{side:13,base:10,h:12},{side:15,base:18,h:12}]);const {side,base,h}=cfg;const area=base*h/2;const left=['Довжина основи AB','Висота трикутника до AB','Площа трикутника ABC'];const values=[base,h,area];const extra1=side,extra2=base+h;let optionVals=unique([...values,extra1,extra2]);while(optionVals.length<5)optionVals.push(String(Number(optionVals[optionVals.length-1])+1));optionVals=shuffle(optionVals.slice(0,5));const code=(v)=>LETTERS[optionVals.indexOf(String(v))];return makeMatching('matching_planimetry',{topic:'planimetry',question:'На рисунку зображено рівнобедрений трикутник. Узгодьте величину (1–3) з її значенням (А–Д).',left,options:optionVals.map(ua),correct_pairs:{'0':code(base),'1':code(h),'2':code(area)},explanation:`Висота ділить основу навпіл. За теоремою Піфагора знаходимо h=${h}, а площа дорівнює ${area}.`,diagram_svg:triangleMatchSvg(side,base)});}

function shortCalculus(){if(Math.random()<.5){const a=pick([2,3,4]),u=pick([2,3]);const val=a*u*u/2+2*u;return makeShort('short_calculus',{topic:'calculus',question:`Обчисліть ${math(`\\int_0^{${u}}(${a}x+2)\\,dx`)}.`,correct_value:val,explanation:`Первісна: ${math(`F(x)=\\frac{${a}}2x^2+2x`)}. Обчислюємо F(${u})−F(0)=${ua(val)}.`});}const x1=pick([-3,-2,-1]),x2=pick([2,3,4]);const a=2;const b=-2*a*(x1+x2)/2;const c=1;const minPoint=Math.max(x1,x2);return makeShort('short_calculus',{topic:'calculus',question:`Функція ${math(`f(x)=x^3-${3*(x1+x2)/2}x^2+${3*x1*x2}x+1`)} має дві критичні точки. Визначте більшу з них.`,correct_value:minPoint,explanation:'Знаходимо похідну, прирівнюємо її до нуля та обираємо більшу критичну точку.'});}
function shortApplied(){const small=pick([500,600,700,800,900]);const p=pick([20,25,40,50]);const large=small*(1+p/100);const total=small+large;return makeShort('short_applied',{topic:'word_problems',question:`Вартість більшого замовлення на ${p}% вища за вартість меншого. Разом вони коштують ${ua(total)} грн. Визначте вартість більшого замовлення.`,correct_value:large,explanation:`Нехай менше коштує x. Тоді більше — ${1+p/100}x, а сума — ${2+p/100}x=${total}. Звідси більше коштує ${large} грн.`});}
function shortStereo(){const k=pick([1,2]);const coneCoeff=100*k*k*k;const answer=900*k*k*k;return makeShort('short_stereometry_linked_solids',{topic:'stereometry',question:`На рисунку зображено правильну трикутну піраміду та конус, у якому радіус основи відноситься до висоти як 5:12. Радіус основи конуса дорівнює радіусу кола, вписаного в основу піраміди, а висота піраміди у ${math('\\sqrt3')} раза більша за висоту конуса. Обчисліть об’єм піраміди, якщо об’єм конуса дорівнює ${math(`${coneCoeff}\\pi`)} см³.`,correct_value:answer,explanation:`Нехай радіус конуса ${math(`r=${5*k}`)}, тоді його висота ${math(`h=${12*k}`)} — це узгоджується з заданим об’ємом ${math(`${coneCoeff}\\pi`)}. Для рівносторонньої основи піраміди ${math(`r=\\frac{a\\sqrt3}{6}`)}, звідки знаходимо сторону і площу основи. Висота піраміди дорівнює ${math(`${12*k}\\sqrt3`)}. Після підстановки у ${math('V=\\frac13S_{осн}H')} отримуємо ${answer}.`,diagram_svg:linkedSolidsSvg()});}
function shortParameter(){let c=pick([-5,-4,-3,-2,2,3,4,5]);let d=pick([-7,-6,-1,1,6,7,8]);while(d===c)d+=1;const answer=c+d;const cTerm=c<0?`(x+${Math.abs(c)})`:`(x-${c})`;const dTerm=d<0?`(x+${Math.abs(d)})`:`(x-${d})`;return makeShort('short_parameter_roots',{topic:'equations',question:`Визначте суму всіх значень параметра ${math('a')}, за кожного з яких рівняння ${math(`\\frac{(x-a)${cTerm}}{${dTerm}}=0`)} має єдиний розв’язок.`,correct_value:answer,explanation:`Область допустимих значень виключає ${math(`x=${d}`)}. Чисельник дає корені ${math('x=a')} та ${math(`x=${c}`)}. Єдиний допустимий корінь маємо у двох випадках: ${math(`a=${c}`)} (корені чисельника збігаються) або ${math(`a=${d}`)} (корінь x=a виключений ОДЗ). Їхня сума: ${c}+${d}=${answer}.`});}

const GEN={data_chart_reading:dataChart,applied_ratio_percent:appliedPercent,planimetry_angle_parallel:planAngle,linear_inequality_pick:linearIneq,solid_geometry_concept:solidConcept,function_graph_transform:functionShift,probability_counting_basic:probabilityBasic,vectors_3d:vectors3d,algebra_simplify:algebraSimplify,geometry_statements:geometryStatements,log_exp_equation_interval:logEquation,calculus_basic:calculusBasic,circle_rectangle_geometry:circleRect,trig_exact_values:trigExact,advanced_single_choice:advancedChoice,quadratic_equation:quadraticChoice,systems_linear:systemLinear,progression_ap:progression,powers_roots_transform:powersRoots,matching_functions:matchingFunctions,matching_expressions:matchingExpressions,matching_planimetry:matchingPlanimetry,short_calculus:shortCalculus,short_applied:shortApplied,short_stereometry_linked_solids:shortStereo,short_parameter_roots:shortParameter};

const TRAINING_BY_TOPIC={
  numbers:['algebra_simplify'], percents:['applied_ratio_percent'], powers_roots:['powers_roots_transform','matching_expressions'], logarithms:['log_exp_equation_interval'], equations:['quadratic_equation'], inequalities:['linear_inequality_pick'], systems:['systems_linear'], functions:['function_graph_transform'], progressions:['progression_ap'], trigonometry:['trig_exact_values'], calculus:['calculus_basic'], probability_stats:['data_chart_reading','probability_counting_basic'], planimetry:['planimetry_angle_parallel','geometry_statements','circle_rectangle_geometry'], stereometry:['solid_geometry_concept','vectors_3d'], word_problems:['applied_ratio_percent'],
};
const TRAINING_ALL=Object.values(TRAINING_BY_TOPIC).flat();

export function generateByBlueprint(id){const fn=GEN[id];if(!fn)throw new Error(`Unknown blueprint ${id}`);return fn();}
export function generateTrainingChoice(topic='mixed',difficulty='середній',avoidList=[]){const pool=topic==='mixed'?TRAINING_ALL:(TRAINING_BY_TOPIC[topic]||TRAINING_ALL);for(let i=0;i<30;i++){const id=pick(pool);const q=generateByBlueprint(id);if(q.type!=='choice')continue;if(avoidList.includes(q.question))continue;return {...q,difficulty};}throw new Error('Could not produce unique training question');}
export function generateExamQuestions(){const qs=EXAM_SLOTS.map(slot=>{const id=pick(slot.blueprint_ids);const q=generateByBlueprint(id);if(q.type!==slot.type)throw new Error(`Slot ${slot.slot}: type mismatch`);return {...q,number:slot.slot,id:`nmt-${slot.slot}-${Date.now()}-${randInt(100,999)}`,engine_version:QUESTION_ENGINE_VERSION};});validateExamQuestions(qs);return qs;}
export function validateQuestion(q){if(!q||!q.question||!q.topic||!q.blueprint_id)return false;if(q.type==='choice'){return Array.isArray(q.options)&&q.options.length===5&&new Set(q.options).size===5&&Number.isInteger(q.correct_index)&&q.correct_index>=0&&q.correct_index<5&&typeof q.explanation==='string'&&q.explanation.length>0;}if(q.type==='matching'){return Array.isArray(q.left)&&q.left.length===3&&Array.isArray(q.match_options)&&q.match_options.length===5&&Object.values(q.correct_pairs||{}).length===3;}if(q.type==='short'){return Number.isFinite(q.correct_value);}return false;}
export function validateExamQuestions(qs){if(!Array.isArray(qs)||qs.length!==22)throw new Error('Exam must contain 22 questions');if(qs.filter(q=>q.type==='choice').length!==15)throw new Error('Need 15 choice');if(qs.filter(q=>q.type==='matching').length!==3)throw new Error('Need 3 matching');if(qs.filter(q=>q.type==='short').length!==4)throw new Error('Need 4 short');if(qs.reduce((s,q)=>s+q.max_score,0)!==32)throw new Error('Need max score 32');qs.forEach((q,i)=>{if(!validateQuestion(q))throw new Error(`Invalid question ${i+1}`)});return true;}
