import { EXAM_SLOTS, QUESTION_BLUEPRINTS } from './nmt-knowledge.js';

export const QUESTION_ENGINE_VERSION = 6;
const LETTERS = ['А','Б','В','Г','Д'];
const LABELS = {
  numbers:'Числа та дроби', percents:'Відсотки та пропорції', powers_roots:'Степені та корені', logarithms:'Логарифми',
  equations:'Рівняння', inequalities:'Нерівності', systems:'Системи рівнянь', functions:'Функції та графіки',
  progressions:'Прогресії', trigonometry:'Тригонометрія', calculus:'Похідна та інтеграл', probability_stats:'Ймовірність і статистика',
  planimetry:'Планіметрія', stereometry:'Стереометрія', word_problems:'Текстові задачі', mixed:'Змішані завдання НМТ'
};
const BLUEPRINTS = new Map(QUESTION_BLUEPRINTS.map(x => [x.id, x]));
const randInt=(a,b)=>Math.floor(Math.random()*(b-a+1))+a;
const pick=(a)=>a[randInt(0,a.length-1)];
function shuffle(arr){const a=[...arr];for(let i=a.length-1;i>0;i--){const j=randInt(0,i);[a[i],a[j]]=[a[j],a[i]];}return a;}
const gcd=(a,b)=>b?gcd(b,a%b):Math.abs(a);
const ua=(n)=>Number.isInteger(Number(n))?String(Number(n)):String(Number(n).toFixed(6)).replace(/0+$/,'').replace(/\.$/,'').replace('.',',');
const math=(s)=>`\\(${s}\\)`;
function frac(n,d){const g=gcd(n,d);n/=g;d/=g;if(d<0){n=-n;d=-d;}return d===1?math(String(n)):math(`\\frac{${n}}{${d}}`);}
function unique(items){return [...new Set(items.map(String))];}
function topicLabel(topic){return LABELS[topic]||topic;}
export function questionSkeleton(text=''){
  return String(text).toLowerCase()
    .replace(/\\\([\s\S]*?\\\)/g,' <math> ')
    .replace(/\d+(?:[.,]\d+)?/g,'#')
    .replace(/[а-яіїєґa-z]+_?\d*/giu,m=>m)
    .replace(/\s+/g,' ').trim();
}
function metadata(id,variant='base'){const b=BLUEPRINTS.get(id)||{};return { blueprint_id:id, variant_key:`${id}:${variant}`, subtopic:b.subtopic||null, skill:b.skill||null, source_confidence:b.source_confidence||2, engine_version:QUESTION_ENGINE_VERSION };}
function makeChoice(id,{topic,question,correct,distractors,explanation,diagram_svg=null,difficulty='середній',variant='base'}){
  let opts=unique([correct,...distractors]); let guard=0;
  while(opts.length<5&&guard++<60) opts=unique([...opts,ua(randInt(-40,120))]);
  opts=shuffle(opts.slice(0,5)); const ci=opts.indexOf(String(correct)); if(ci<0) throw new Error('correct option lost');
  return {type:'choice',topic,topic_label:topicLabel(topic),difficulty,question,options:opts,correct_index:ci,explanation,max_score:1,diagram_svg,question_skeleton:questionSkeleton(question),...metadata(id,variant)};
}
function makeMatching(id,{topic,question,left,options,correct_pairs,explanation,diagram_svg=null,variant='base'}){
  return {type:'matching',topic,topic_label:topicLabel(topic),question,left,match_options:options.map((label,i)=>({code:LETTERS[i],label:String(label)})),correct_pairs,explanation,max_score:3,diagram_svg,question_skeleton:questionSkeleton(question),...metadata(id,variant)};
}
function makeShort(id,{topic,question,correct_value,explanation,diagram_svg=null,answer_hint='Введи число',variant='base'}){
  return {type:'short',topic,topic_label:topicLabel(topic),question,correct_value:Number(correct_value),correct_display:ua(correct_value),explanation,max_score:2,diagram_svg,answer_hint,question_skeleton:questionSkeleton(question),...metadata(id,variant)};
}

function shellSvg(inner, aria='Математична схема', view='0 0 420 280'){
  return `<svg viewBox="${view}" role="img" aria-label="${aria}" xmlns="http://www.w3.org/2000/svg"><defs><style>.g{stroke:#24262a;stroke-width:2.6;fill:none;stroke-linecap:round;stroke-linejoin:round}.d{stroke:#918776;stroke-width:1.8;fill:none;stroke-dasharray:6 6}.a{stroke:#b88c3b;stroke-width:2.7;fill:none}.f{fill:#f6eddc;stroke:#b88c3b;stroke-width:1.5}.t{font:700 16px -apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;fill:#24262a}.m{font:600 13px -apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;fill:#66645f}.s{font:600 12px -apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;fill:#8d8477}.grid{stroke:#e6e0d5;stroke-width:1}.tick{stroke:#aaa192;stroke-width:1.2}</style></defs>${inner}</svg>`;
}
function axesSvg(points,extra=''){
  let grid='';for(let x=50;x<=370;x+=40)grid+=`<path class="grid" d="M${x} 30V240"/>`;for(let y=40;y<=240;y+=40)grid+=`<path class="grid" d="M40 ${y}H380"/>`;
  return shellSvg(`${grid}<path class="g" d="M40 140H382 M210 25V245"/><path class="g" d="M382 140l-8-5m8 5l-8 5M210 25l-5 8m5-8l5 8"/>${points}${extra}<text class="m" x="384" y="134">x</text><text class="m" x="218" y="30">y</text><text class="s" x="216" y="156">0</text>`,'Координатна площина');
}
function barChartSvg(values,labels){const max=Math.max(...values);let grid='';for(let i=0;i<5;i++){const y=215-i*40;grid+=`<path class="grid" d="M48 ${y}H390"/>`;}
 const bars=values.map((v,i)=>{const h=145*v/max,x=76+i*72,y=215-h;return `<rect x="${x}" y="${y}" width="38" height="${h}" rx="5" fill="#c8a35c"/><text class="m" x="${x+19}" y="${y-8}" text-anchor="middle">${v}</text><text class="m" x="${x+19}" y="242" text-anchor="middle">${labels[i]}</text>`}).join('');return shellSvg(`${grid}<path class="g" d="M48 215H390 M48 42V215"/>${bars}<text class="s" x="20" y="50" transform="rotate(-90 20 50)">Кількість</text>`,'Стовпчаста діаграма');}
function lineChartSvg(vals){const max=Math.max(...vals)+2,min=Math.min(...vals)-2;const sy=v=>210-(v-min)/(max-min)*145;const pts=vals.map((v,i)=>`${70+i*55},${sy(v)}`).join(' ');let grid='';for(let i=0;i<6;i++){const x=70+i*55;grid+=`<path class="grid" d="M${x} 45V215"/><text class="s" x="${x}" y="238" text-anchor="middle">${i+1}</text>`;}for(let y=55;y<=215;y+=40)grid+=`<path class="grid" d="M50 ${y}H365"/>`;return shellSvg(`${grid}<path class="g" d="M50 215H370 M50 40V215"/><polyline points="${pts}" fill="none" stroke="#b88c3b" stroke-width="3"/>${vals.map((v,i)=>`<circle cx="${70+i*55}" cy="${sy(v)}" r="4" fill="#24262a"/><text class="s" x="${70+i*55}" y="${sy(v)-10}" text-anchor="middle">${v}</text>`).join('')}<text class="s" x="190" y="260">Період</text>`,'Лінійний графік');}
function trapezoidSvg(top,bottom,h,angle=null){const left=78,right=342,topY=66,botY=222,shift=(bottom-top)/bottom*70;const x1=78+shift,x2=342-shift;return shellSvg(`<path class="g" d="M78 222 L342 222 L${x2} 66 L${x1} 66 Z"/><path class="d" d="M${x1} 66V222"/><path class="g" d="M${x1} 210h12v12"/><text class="t" x="62" y="244">A</text><text class="t" x="346" y="244">D</text><text class="t" x="${x1-8}" y="55">B</text><text class="t" x="${x2+4}" y="55">C</text><text class="m" x="194" y="252">${bottom}</text><text class="m" x="194" y="56">${top}</text><text class="m" x="${x1+8}" y="150">${h}</text>${angle?`<path class="a" d="M305 222 A34 34 0 0 0 326 190"/><text class="m" x="292" y="188">${angle}°</text>`:''}`,'Трапеція');}
function triangleCosSvg(a,b,ang,c){return shellSvg(`<path class="g" d="M62 222 L350 222 L150 52 Z"/><path class="a" d="M95 222 A34 34 0 0 0 85 197"/><text class="m" x="96" y="190">${ang}°</text><text class="t" x="48" y="244">A</text><text class="t" x="354" y="244">B</text><text class="t" x="142" y="44">C</text><text class="m" x="192" y="247">${c}</text><text class="m" x="88" y="130">${b}</text><text class="m" x="270" y="132">${a}</text>`,'Трикутник із заданими сторонами і кутом');}
function circleAngleSvg(centerDeg,inscribedDeg){return shellSvg(`<circle class="g" cx="210" cy="140" r="96"/><circle cx="210" cy="140" r="4" fill="#24262a"/><path class="g" d="M210 140L210 44 M210 140L294 187 M210 44L126 187L294 187"/><path class="a" d="M210 92 A48 48 0 0 1 251 164"/><text class="m" x="247" y="115">${centerDeg}°</text><path class="a" d="M145 178 A24 24 0 0 1 151 160"/><text class="m" x="127" y="155">?</text><text class="t" x="203" y="34">A</text><text class="t" x="112" y="205">B</text><text class="t" x="302" y="205">C</text><text class="t" x="218" y="137">O</text>`,'Коло з центральним та вписаним кутами');}
function similarTrianglesSvg(k){return shellSvg(`<path class="g" d="M55 222L190 58L190 222Z M238 222L352 84L352 222Z"/><path class="g" d="M178 210h12v12 M340 210h12v12"/><path class="a" d="M55 222L190 58 M238 222L352 84"/><text class="t" x="42" y="244">A</text><text class="t" x="186" y="47">B</text><text class="t" x="192" y="244">C</text><text class="t" x="228" y="244">D</text><text class="t" x="348" y="72">E</text><text class="t" x="356" y="244">F</text><text class="m" x="105" y="244">${k*3}</text><text class="m" x="276" y="244">${k*2}</text>`,'Подібні прямокутні трикутники');}
function prismSvg(a,b,h){return shellSvg(`<path class="g" d="M72 210L278 210L345 160L140 160Z M72 94L278 94L345 44L140 44Z M72 94V210 M278 94V210 M345 44V160 M140 44V160"/><path class="d" d="M72 210L345 44"/><text class="m" x="164" y="232">${a}</text><text class="m" x="309" y="190">${b}</text><text class="m" x="50" y="154">${h}</text><text class="s" x="184" y="122">просторова діагональ</text>`,'Прямокутний паралелепіпед');}
function cylinderPrismSvg(){return shellSvg(`<ellipse class="g" cx="112" cy="208" rx="66" ry="20"/><ellipse class="g" cx="112" cy="72" rx="66" ry="20"/><path class="g" d="M46 72V208 M178 72V208"/><path class="g" d="M238 220L350 220L294 184Z M238 82L350 82L294 46Z M238 82V220 M350 82V220 M294 46V184"/><path class="d" d="M294 46V220"/><text class="m" x="72" y="258">циліндр</text><text class="m" x="266" y="258">призма</text>`,'Циліндр і призма');}
function functionParabolaSvg(root1,root2){const center=(root1+root2)/2, scale=35;const pts=[];for(let x=-4;x<=4;x+=.15){const y=.45*(x-root1)*(x-root2);pts.push(`${210+x*scale},${140-y*18}`);}return axesSvg(`<polyline points="${pts.join(' ')}" fill="none" stroke="#b88c3b" stroke-width="3"/>`,`<text class="s" x="${210+root1*scale}" y="160" text-anchor="middle">${root1}</text><text class="s" x="${210+root2*scale}" y="160" text-anchor="middle">${root2}</text>`);}

// --- Single-choice blueprints ---
function dataChart(){
  if(Math.random()<.5){const vals=[randInt(4,9),randInt(7,13),randInt(10,17),randInt(5,12)];const total=vals.reduce((a,b)=>a+b,0);return makeChoice('data_chart_reading',{topic:'probability_stats',variant:'bar-total',question:'На діаграмі подано кількість учасників у чотирьох групах. Скільки всього учасників охоплено діаграмою?',correct:ua(total),distractors:[ua(total-vals[0]),ua(total+vals[0]),ua(Math.max(...vals)),ua(vals[1]+vals[2])],explanation:`Додаємо значення всіх стовпчиків: ${vals.join(' + ')} = ${total}.`,diagram_svg:barChartSvg(vals,['I','II','III','IV']),difficulty:'легкий'});}
  const vals=[randInt(7,12),randInt(10,16),randInt(8,14),randInt(13,19),randInt(9,15),randInt(6,12)];const threshold=pick(vals);const count=vals.filter(v=>v>=threshold).length;return makeChoice('data_chart_reading',{topic:'probability_stats',variant:'line-threshold',question:`На графіку показано значення показника протягом шести періодів. У скількох періодах значення було не меншим за ${threshold}?`,correct:ua(count),distractors:[ua(Math.max(1,count-1)),ua(count+1),ua(6-count),ua(threshold)],explanation:`Переглядаємо шість точок і рахуємо ті, де значення ≥ ${threshold}. Таких періодів ${count}.`,diagram_svg:lineChartSvg(vals),difficulty:'легкий'});
}
function appliedPercent(){const scene=randInt(0,2);if(scene===0){const final=pick([84,105,126,140,168,210]);const discount=pick([20,25,30,40]);const original=final/(1-discount/100);if(!Number.isInteger(original))return appliedPercent();return makeChoice('applied_ratio_percent',{topic:'percents',variant:'reverse-discount',question:`Після знижки ${discount}% товар коштує ${final} грн. Якою була його ціна до знижки?`,correct:ua(original),distractors:[ua(final/(discount/100)),ua(final*(1+discount/100)),ua(final+discount),ua(original-final)],explanation:`Після знижки залишилося ${100-discount}% початкової ціни. Тому початкова ціна: ${final}/(${(100-discount)/100}) = ${original} грн.`});}
 if(scene===1){const a=pick([120,160,200,240,300]);const inc=pick([10,20,25]);const dec=pick([10,20]);const after=a*(1+inc/100)*(1-dec/100);return makeChoice('applied_ratio_percent',{topic:'percents',variant:'successive-change',question:`Величину ${a} спочатку збільшили на ${inc}%, а потім отриманий результат зменшили на ${dec}%. Яке значення одержали?`,correct:ua(after),distractors:[ua(a*(1+(inc-dec)/100)),ua(a*(1+inc/100)),ua(a*(1-dec/100)),ua(after+a/10)],explanation:`Послідовні відсоткові зміни множаться: ${a}·${1+inc/100}·${1-dec/100} = ${ua(after)}.`});}
 const total=pick([360,480,600,720,900]), part=pick([2,3,4]), denom=pick([5,6,8]);if(part>=denom)return appliedPercent();const spent=total*part/denom;if(!Number.isInteger(spent))return appliedPercent();return makeChoice('applied_ratio_percent',{topic:'percents',variant:'fraction-context',question:`Із ${total} грн витратили ${part}/${denom} усієї суми. Скільки гривень залишилося?`,correct:ua(total-spent),distractors:[ua(spent),ua(total/denom),ua(total*(denom-part)/part),ua(total-part/denom)],explanation:`Витрачено ${total}·${part}/${denom}=${spent}. Залишилося ${total-spent} грн.`});}
function planAngle(){if(Math.random()<.5){const c=pick([100,110,120,130,140]);const a=180-c;return makeChoice('planimetry_angle_parallel',{topic:'planimetry',variant:'isosceles-trapezoid-angle',question:`На рисунку зображено рівнобічну трапецію ABCD. Визначте ∠BAD, якщо ∠BCD = ${c}°.` ,correct:`${a}°`,distractors:[`${c}°`,`${180-a/2}°`,`${a/2}°`,`${90+a/2}°`],explanation:`Кути при кожній основі рівнобічної трапеції рівні, а прилеглі до бічної сторони — суміжні. Тому ∠BAD = 180° − ${c}° = ${a}° .`,diagram_svg:trapezoidSvg(10,18,8,c),difficulty:'середній'});}
 const A=pick([35,40,45,50]),B=pick([55,60,65,70]),C=180-A-B;return makeChoice('planimetry_angle_parallel',{topic:'planimetry',variant:'triangle-exterior',question:`У трикутнику ABC ∠A=${A}°, ∠B=${B}°. Через вершину C проведено пряму, паралельну AB. Визначте гострий кут між цією прямою та стороною AC.`,correct:`${A}°`,distractors:[`${B}°`,`${C}°`,`${180-A}°`,`${180-B}°`],explanation:'За властивістю внутрішніх різносторонніх кутів кут між AC і прямою через C, паралельною AB, дорівнює ∠A.',diagram_svg:triangleCosSvg(8,7,A,9),difficulty:'середній'});}
function triangleCosine(){const triples=pick([{a:7,b:8,ang:60,c:Math.sqrt(57)},{a:5,b:7,ang:60,c:Math.sqrt(39)},{a:6,b:10,ang:120,c:14},{a:8,b:15,ang:60,c:13}]);const {a,b,ang,c}=triples;const c2=Math.round(c*c);const correct=Number.isInteger(c)?ua(c):math(`\\sqrt{${c2}}`);return makeChoice('triangle_cosine_nmt',{topic:'planimetry',variant:`cos-${ang}`,question:`У трикутнику ABC відомо: AC=${b}, BC=${a}, ∠ACB=${ang}°. Знайдіть AB.`,correct,distractors:[ua(a+b),ua(Math.abs(a-b)),math(`\\sqrt{${a*a+b*b}}`),math(`\\sqrt{${a*a+b*b+ a*b}}`)],explanation:`За теоремою косинусів: ${math(`AB^2=${a}^2+${b}^2-2\\cdot${a}\\cdot${b}\\cos${ang}^\\circ=${c2}`)}.`,diagram_svg:triangleCosSvg(a,b,ang,ua(c)),difficulty:'складний'});}
function circleAngle(){const central=pick([80,100,120,140,160]);const ins=central/2;return makeChoice('circle_inscribed_angle',{topic:'planimetry',variant:'central-inscribed',question:`На рисунку центральний кут AOC дорівнює ${central}°. Знайдіть вписаний кут ABC, який спирається на ту саму дугу AC.`,correct:`${ins}°`,distractors:[`${central}°`,`${180-central}°`,`${90-ins}°`,`${180-ins}°`],explanation:`Вписаний кут, що спирається на ту саму дугу, дорівнює половині центрального: ${central}/2=${ins}° .`,diagram_svg:circleAngleSvg(central,ins),difficulty:'середній'});}
function similarTriangles(){const k=pick([2,3,4]);const x=6*k/2;return makeChoice('similar_triangles_ratio',{topic:'planimetry',variant:'two-right-triangles',question:`Два прямокутні трикутники на рисунку подібні. У більшого трикутника основа ${3*k}, а відповідна основа меншого — ${2*k}. Якщо відповідна висота меншого дорівнює 6, знайдіть висоту більшого.`,correct:ua(9),distractors:[ua(6*k/2),ua(6*2/3),ua(6+ k),ua(12)],explanation:`Коефіцієнт подібності більшого до меншого: ${(3*k)}/${(2*k)}=3/2. Отже висота більшого: 6·3/2=9.`,diagram_svg:similarTrianglesSvg(k),difficulty:'середній'});}
function linearIneq(){const a=pick([2,3,4,5]), bound=pick([-3,-2,2,3,4,5]), b=pick([-5,-2,1,3,7]), rhs=a*bound+b;const choices=shuffle([bound-2,bound-1,bound,bound+1,bound+2]);const correct=Math.min(...choices.filter(x=>a*x+b>rhs));return makeChoice('linear_inequality_pick',{topic:'inequalities',variant:'pick-smallest',question:`Позначте з наведених найменше число, яке є розв’язком нерівності ${math(`${a}x${b>=0?'+':''}${b}>${rhs}`)}.`,correct:ua(correct),distractors:choices.filter(x=>x!==correct).map(ua),explanation:`Маємо ${math(`${a}x>${rhs-b}`)}, тобто ${math(`x>${bound}`)}. Серед запропонованих найменше допустиме число — ${correct}.`});}
function quadraticIneq(){const r1=pick([-5,-4,-3,-2]),r2=pick([1,2,3,4,5]);return makeChoice('quadratic_inequality_interval',{topic:'inequalities',variant:'sign-interval',question:`Розв’яжіть нерівність ${math(`(x-${r1})(x-${r2})<0`)}.`,correct:`(${r1}; ${r2})`,distractors:[`(−∞; ${r1})∪(${r2}; +∞)`,`[${r1}; ${r2}]`,`(−∞; ${r2})`,`(${r1}; +∞)`],explanation:`Добуток двох лінійних множників від’ємний між коренями ${r1} і ${r2}.`,difficulty:'середній'});}
function solidConcept(){const v=randInt(0,2);if(v===0)return makeChoice('solid_geometry_concept',{topic:'stereometry',variant:'rotation',question:'Яке тіло утвориться внаслідок обертання прямокутного трикутника навколо одного з його катетів?',correct:'конус',distractors:['циліндр','куля','призма','піраміда'],explanation:'При обертанні прямокутного трикутника навколо катета другий катет утворює кругову основу, а гіпотенуза — бічну поверхню конуса.',difficulty:'легкий'});
 if(v===1)return makeChoice('solid_geometry_concept',{topic:'stereometry',variant:'parallel-plane',question:'Через точку, що не належить даній площині, скільки можна провести площин, паралельних даній?',correct:'лише одну',distractors:['жодної','лише дві','лише три','нескінченно багато'],explanation:'Через точку поза площиною проходить рівно одна площина, паралельна даній.',difficulty:'середній'});
 const a=pick([3,4,5]),b=pick([4,6,8]),h=pick([6,8,12]);const d2=a*a+b*b+h*h;return makeChoice('solid_geometry_concept',{topic:'stereometry',variant:'box-diagonal',question:`Прямокутний паралелепіпед має ребра ${a}, ${b} і ${h}. Знайдіть квадрат довжини його просторової діагоналі.`,correct:ua(d2),distractors:[ua(a*a+b*b),ua(a+b+h),ua(2*(a*b+b*h+a*h)),ua(a*b*h)],explanation:`Для просторової діагоналі ${math(`d^2=${a}^2+${b}^2+${h}^2=${d2}`)}.`,diagram_svg:prismSvg(a,b,h),difficulty:'середній'});}
function functionShift(){const mode=randInt(0,2);if(mode===0){const shift=pick([-3,-2,2,3]);const correct=shift>0?`y=f(x-${shift})`:`y=f(x+${Math.abs(shift)})`;return makeChoice('function_graph_transform',{topic:'functions',variant:'horizontal-shift',question:`Графік ${math('y=f(x)')} перенесли на ${Math.abs(shift)} одиниці ${shift>0?'вправо':'вліво'}. Яке рівняння має новий графік?`,correct:math(correct),distractors:[math(`y=f(x${shift>0?'+':'-'}${Math.abs(shift)})`),math(`y=f(x)+${Math.abs(shift)}`),math(`y=f(x)-${Math.abs(shift)}`),math(`y=${Math.abs(shift)}f(x)`) ],explanation:`Горизонтальний зсув вправо на a задається ${math('y=f(x-a)')}, вліво — ${math('y=f(x+a)')}.`,diagram_svg:functionParabolaSvg(-1+Math.sign(shift),1+Math.sign(shift)),difficulty:'середній'});}
 if(mode===1){const r1=pick([-3,-2,-1]),r2=pick([1,2,3]);return makeChoice('function_graph_transform',{topic:'functions',variant:'graph-sign',question:'За графіком квадратичної функції визначте проміжок, на якому функція набуває від’ємних значень.',correct:`(${r1}; ${r2})`,distractors:[`(−∞; ${r1})∪(${r2}; +∞)`,`[${r1}; ${r2}]`,`(−∞; ${r2})`,`(${r1}; +∞)`],explanation:'Парабола відкрита вгору, тому її значення від’ємні між нулями функції.',diagram_svg:functionParabolaSvg(r1,r2),difficulty:'середній'});}
 const x=pick([1,2,3]);return makeChoice('function_graph_transform',{topic:'functions',variant:'odd-function',question:`Функція f є непарною і ${math(`f(${x})=${2*x+1}`)}. Знайдіть ${math(`f(-${x})`)}.`,correct:ua(-(2*x+1)),distractors:[ua(2*x+1),ua(-2*x+1),ua(2*x-1),ua(-x)],explanation:`Для непарної функції ${math('f(-x)=-f(x)')}.`,difficulty:'середній'});}
function probabilityBasic(){const v=randInt(0,2);if(v===0){const nature=randInt(5,9),buildings=randInt(4,8),people=randInt(3,6),total=nature+buildings+people,fav=nature+buildings;return makeChoice('probability_counting_basic',{topic:'probability_stats',variant:'categories-or',question:`У наборі ${total} карток: ${nature} зелених, ${people} синіх і ${buildings} жовтих. Яка ймовірність навмання вибрати зелену або жовту картку?`,correct:frac(fav,total),distractors:[frac(nature,total),frac(buildings,total),frac(people,total),frac(fav,total-people)],explanation:`Сприятливих карток ${nature}+${buildings}=${fav}, усього ${total}. Ймовірність ${fav}/${total}.`,difficulty:'середній'});}
 if(v===1){const red=pick([3,4,5,6]),blue=pick([4,5,6,7]);const total=red+blue;const num=red*(red-1),den=total*(total-1);return makeChoice('probability_counting_basic',{topic:'probability_stats',variant:'without-replacement',question:`У коробці ${red} червоних і ${blue} синіх кульок. Навмання без повернення витягують дві кульки. Яка ймовірність, що обидві будуть червоними?`,correct:frac(num,den),distractors:[frac(red,total),frac(red*red,total*total),frac(red*blue,den),frac((red-1),(total-1))],explanation:`Ймовірність першої червоної ${red}/${total}, а другої — ${red-1}/${total-1}. Перемножуємо.`,difficulty:'складний'});}
 const n=pick([5,6,7,8]);const pairs=n*(n-1)/2;return makeChoice('probability_counting_basic',{topic:'probability_stats',variant:'pair-count',question:`У групі ${n} учнів потрібно вибрати двох представників. Скількома способами це можна зробити?`,correct:ua(pairs),distractors:[ua(n*n),ua(n*(n-1)),ua(n+2),ua(Math.max(1,pairs-n))],explanation:`Порядок неважливий, тому кількість пар ${math(`C_{${n}}^2=${n}\\cdot${n-1}/2=${pairs}`)}.`,difficulty:'середній'});}
function vectors3d(){const v=randInt(0,1);if(v===0){const a=[randInt(-3,3),randInt(-3,3),randInt(-2,2)],b=[randInt(-3,4),randInt(-3,4),randInt(-2,3)],c=a.map((x,i)=>x+b[i]),mag2=c.reduce((s,x)=>s+x*x,0);return makeChoice('vectors_3d',{topic:'stereometry',variant:'vector-sum-length',question:`Задано вектори ${math(`\\vec a=(${a.join(';')})`)} і ${math(`\\vec b=(${b.join(';')})`)}. Визначте ${math('|\\vec a+\\vec b|^2')}.`,correct:ua(mag2),distractors:[ua(mag2+1),ua(Math.abs(c[0])+Math.abs(c[1])+Math.abs(c[2])),ua(a.reduce((s,x)=>s+x*x,0)),ua(b.reduce((s,x)=>s+x*x,0))],explanation:`${math(`\\vec a+\\vec b=(${c.join(';')})`)}, тому квадрат модуля — сума квадратів координат: ${mag2}.`,difficulty:'середній'});}
 const A=[randInt(-3,2),randInt(-3,2),randInt(-2,2)],B=[A[0]+randInt(2,6),A[1]+randInt(2,6),A[2]+randInt(-3,3)],C=B.map((x,i)=>2*x-A[i]);return makeChoice('vectors_3d',{topic:'stereometry',variant:'central-symmetry-3d',question:`У просторі A(${A.join('; ')}) і B(${B.join('; ')}). Точка C симетрична точці A відносно B. Знайдіть координати C.`,correct:`(${C.join('; ')})`,distractors:[`(${B.map((x,i)=>x-A[i]).join('; ')})`,`(${A.map((x,i)=>2*x-B[i]).join('; ')})`,`(${A.map((x,i)=>x+B[i]).join('; ')})`,`(${C.map(x=>-x).join('; ')})`],explanation:'Оскільки B — середина AC, маємо C=2B−A по кожній координаті.',difficulty:'середній'});}
function algebraSimplify(){const mode=randInt(0,2);if(mode===0){const k=pick([3,4,5,6]),m=pick([2,3,5]);const correct=`${k}x+${m*m}`;return makeChoice('algebra_simplify',{topic:'numbers',variant:'difference-squares',question:`Спростіть ${math(`${k}x-(x-${m})(x+${m})+x^2`)}.`,correct:math(correct),distractors:[math(`${k}x-${m*m}`),math(`${k*m}x+${m*m}`),math(`${k*m}x-${m*m}`),math(`${k}x-x^2`) ],explanation:`${math(`(x-${m})(x+${m})=x^2-${m*m}`)}. Після зведення подібних членів отримуємо ${math(correct)}.`});}
 if(mode===1){const a=pick([2,3,4]),b=pick([2,3,5]);return makeChoice('algebra_simplify',{topic:'numbers',variant:'fraction-combine',question:`Обчисліть ${math(`\\frac{${a}}{${b}}+\\frac{${b}}{${a}}`)}.`,correct:frac(a*a+b*b,a*b),distractors:[frac(a+b,a*b),frac(a+b,a+b),frac(a*b,a*a+b*b),frac(a*a-b*b,a*b)],explanation:`Зводимо до спільного знаменника ${a*b}: чисельник ${a*a}+${b*b}=${a*a+b*b}.`});}
 const a=pick([2,3,5]),n=pick([3,4]);return makeChoice('algebra_simplify',{topic:'numbers',variant:'powers-quotient',question:`Спростіть ${math(`\\frac{${a}^{${n+2}}}{${a}^{${n-1}}}`)}.`,correct:math(`${a}^3`),distractors:[math(`${a}^{${2*n+1}}`),math(`${a}`),math(`${a}^{${n+1}}`),ua(3)],explanation:'Під час ділення степенів з однаковою основою показники віднімаємо.'});}
function geometryStatements(){const variants=[
 {q:'Які твердження правильні? І. Діаметр є найбільшою хордою кола. ІІ. Рівні хорди стягують рівні дуги. ІІІ. Будь-яка хорда більша за радіус.',c:'лише І та ІІ',e:'І та ІІ правильні. ІІІ хибне, бо короткі хорди можуть бути меншими за радіус.'},
 {q:'Які твердження правильні для будь-якого трикутника? І. Більша сторона лежить напроти більшого кута. ІІ. Сума двох сторін більша за третю. ІІІ. Усі медіани є висотами.',c:'лише І та ІІ',e:'І та ІІ — загальні властивості трикутника. ІІІ виконується не для кожного трикутника.'},
 {q:'Які твердження правильні? І. Діагоналі прямокутника рівні. ІІ. Діагоналі ромба перпендикулярні. ІІІ. Діагоналі будь-якої трапеції рівні.',c:'лише І та ІІ',e:'І і ІІ правильні. Діагоналі рівні лише в рівнобічній трапеції, не в довільній.'}
 ];const v=pick(variants);return makeChoice('geometry_statements',{topic:'planimetry',variant:String(variants.indexOf(v)),question:v.q,correct:v.c,distractors:['лише І','лише ІІ','лише ІІІ','І, ІІ та ІІІ'],explanation:v.e,difficulty:'середній'});}
function logEquation(){const mode=randInt(0,2);if(mode===0){const base=pick([2,3,5]),power=pick([2,3]),root=base**power;return makeChoice('log_exp_equation_interval',{topic:'logarithms',variant:'basic-log-root',question:`Якому проміжку належить корінь рівняння ${math(`\\log_{${base}}x=${power}`)}?`,correct:`[${root}; ${root+2})`,distractors:[`(0; ${root-1}]`,`[${root-1}; ${root})`,`[${root+2}; ${root+8})`,`[${root+8}; ${root+20})`],explanation:`Корінь: ${math(`x=${base}^{${power}}=${root}`)}.`});}
 if(mode===1){const b=pick([2,3]),k=pick([1,2,3]),x=b**k-1;return makeChoice('log_exp_equation_interval',{topic:'logarithms',variant:'shifted-log',question:`Розв’яжіть рівняння ${math(`\\log_{${b}}(x+1)=${k}`)}.`,correct:ua(x),distractors:[ua(b*k-1),ua(b**k+1),ua(k**b-1),ua(x+1)],explanation:`${math(`x+1=${b}^{${k}}`)}, тому x=${x}.`});}
 const b=pick([2,3,5]),p=pick([2,3]);const rhs=b**p;return makeChoice('log_exp_equation_interval',{topic:'logarithms',variant:'log-inequality',question:`Розв’яжіть нерівність ${math(`\\log_{${b}}x<${p}`)}.`,correct:`(0; ${rhs})`,distractors:[`(${rhs}; +∞)`,`(−∞; ${rhs})`,`[0; ${rhs}]`,`(0; ${p})`],explanation:`Основа ${b}>1, тому знак зберігається: 0<x<${b}^${p}=${rhs}.`,difficulty:'середній'});}
function calculusBasic(){const mode=randInt(0,2);if(mode===0){const a=pick([2,3,4,5]),b=pick([-4,-2,2,4]),x0=pick([-2,-1,1,2]),val=2*a*x0+b;return makeChoice('calculus_basic',{topic:'calculus',variant:'derivative-point',question:`Обчисліть ${math(`f'(${x0})`)}, якщо ${math(`f(x)=${a}x^2${b>=0?'+':''}${b}x+1`)}.`,correct:ua(val),distractors:[ua(val+2*a),ua(a*x0+b),ua(2*a+b),ua(val-b)],explanation:`${math(`f'(x)=${2*a}x${b>=0?'+':''}${b}`)}; підставляємо x=${x0}.`});}
 if(mode===1){const a=pick([2,3,4]),n=pick([2,3,4]);return makeChoice('calculus_basic',{topic:'calculus',variant:'antiderivative',question:`Укажіть загальний вигляд первісних для ${math(`f(x)=${a*n}x^{${n-1}}`)}.`,correct:math(`${a}x^${n}+C`),distractors:[math(`${a*n}x^${n}+C`),math(`${a}x^${n-1}+C`),math(`${a*n*(n-1)}x^${n-2}+C`),math(`${a}x+C`)],explanation:`Похідна ${math(`${a}x^${n}`)} дорівнює ${math(`${a*n}x^{${n-1}}`)}.`});}
 const a=pick([1,2,3]),u=pick([2,3,4]);const val=a*u*u+2*u;return makeChoice('calculus_basic',{topic:'calculus',variant:'definite-integral',question:`Обчисліть ${math(`\\int_0^{${u}}(2${a}x+2)\\,dx`)}.`,correct:ua(val),distractors:[ua(val+u),ua(a*u*u),ua(2*a*u+2),ua(val-2*u)],explanation:`Первісна ${math(`${a}x^2+2x`)}. Значення на [0;${u}] дорівнює ${val}.`,difficulty:'середній'});}
function circleRect(){if(Math.random()<.5){const r=pick([6,8,10,12]),od=2*r;const correct=math(`${r}(1+\\sqrt3)`);return makeChoice('circle_rectangle_geometry',{topic:'planimetry',variant:'tangent-circle-rectangle',question:`У прямокутнику ABCD коло з центром O дотикається AB і AD. Відомо ${math(`OD=${od}`)} та ${math('\\angle ADO=30^\\circ')}. Знайдіть AD.`,correct,distractors:[math(`${r}\\sqrt3`),math(`${2*r}`),math(`${r}(2+\\sqrt3)`),math(`${2*r}\\sqrt3`)],explanation:`З умови OD=${od} і кута 30° знаходимо радіус ${r}, далі з прямокутного трикутника отримуємо ${math(`AD=${r}(1+\\sqrt3)`)}.`,diagram_svg:circleAngleSvg(60,30),difficulty:'складний'});}
 return triangleCosine();}
function trigExact(){const variants=[{q:math('2\\sin(-\\pi/2)+\\cos(3\\pi)'),c:'-3',d:['-2','-1','2','3']},{q:math('\\sin(\\pi/6)+\\cos(\\pi/3)'),c:'1',d:['0','1/2','√2','2']},{q:math('2\\cos(0)-\\sin(\\pi/2)'),c:'1',d:['-1','0','2','3']},{q:math('\\tan(\\pi/4)+2\\cos(\\pi)'),c:'-1',d:['0','1','2','-2']}];const v=pick(variants);return makeChoice('trig_exact_values',{topic:'trigonometry',variant:String(variants.indexOf(v)),question:`Обчисліть ${v.q}.`,correct:v.c,distractors:v.d,explanation:'Підставляємо точні значення тригонометричних функцій стандартних кутів.',difficulty:'середній'});}
function quadraticChoice(){const r1=pick([-5,-4,-3,-2,1,2]),r2=pick([3,4,5,6]);const s=r1+r2,p=r1*r2;const ask=Math.random()<.5;return makeChoice('quadratic_equation',{topic:'equations',variant:ask?'roots-difference':'roots-sum',question:`Корені рівняння ${math(`x^2${-s>=0?'+':''}${-s}x${p>=0?'+':''}${p}=0`)} дорівнюють x₁ і x₂, де x₂>x₁. Знайдіть ${ask?'x₂−x₁':'x₁+x₂'}.`,correct:ua(ask?Math.abs(r2-r1):s),distractors:[ua(p),ua(Math.abs(s)),ua(Math.abs(r2-r1)+(ask?1:2)),ua(r2)],explanation:`За теоремою Вієта корені — ${r1} і ${r2}. Обчислюємо потрібний вираз.`,difficulty:'середній'});}
function systemLinear(){const x=randInt(2,7),y=randInt(1,6),s=x+y,d=x-y;return makeChoice('systems_linear',{topic:'systems',variant:'sum-difference',question:`Система ${math(`\\begin{cases}x+y=${s}\\\\x-y=${d}\\end{cases}`)} має розв’язок (x;y). Знайдіть ${math('2x+y')}.`,correct:ua(2*x+y),distractors:[ua(s),ua(x),ua(x-y),ua(x*y)],explanation:`Додаємо рівняння, знаходимо x=${x}, y=${y}, тоді 2x+y=${2*x+y}.`,difficulty:'середній'});}
function progression(){const mode=randInt(0,1);const a1=randInt(2,8),d=randInt(2,6),n=randInt(5,10),an=a1+(n-1)*d,sum=n*(a1+an)/2;if(mode===0)return makeChoice('progression_ap',{topic:'progressions',variant:'sum-ap',question:`В арифметичній прогресії ${math(`a_1=${a1}`)}, ${math(`d=${d}`)}. Знайдіть ${math(`S_{${n}}`)}.`,correct:ua(sum),distractors:[ua(an),ua(sum+d),ua(n*(a1+d)),ua(sum-n)],explanation:`Знаходимо ${math(`a_${n}=${an}`)}, потім ${math(`S_${n}=\\frac{${n}(${a1}+${an})}{2}=${sum}`)}.`});return makeChoice('progression_ap',{topic:'progressions',variant:'nth-ap',question:`В арифметичній прогресії ${math(`a_1=${a1}`)} і ${math(`a_${n}=${an}`)}. Знайдіть різницю d.`,correct:ua(d),distractors:[ua(an-a1),ua((an-a1)/n),ua(a1+d),ua(n*d)],explanation:`${math(`a_n=a_1+(n-1)d`)}, тому ${math(`d=(${an}-${a1})/${n-1}=${d}`)}.`});}
function powersRoots(){const mode=randInt(0,2);const a=pick([2,3,5]);if(mode===0){const n=pick([2,3,4]),result=a**n;return makeChoice('powers_roots_transform',{topic:'powers_roots',variant:'sqrt-square',question:`Обчисліть ${math(`\\sqrt{${result*result}}`)}.`,correct:ua(result),distractors:[ua(result*result),ua(a*n),ua(result/a),ua(result+a)],explanation:`Арифметичний квадратний корінь із ${result*result} дорівнює ${result}.`,difficulty:'легкий'});}if(mode===1){const n=pick([4,5,6]);return makeChoice('powers_roots_transform',{topic:'powers_roots',variant:'power-laws',question:`Спростіть ${math(`\\frac{${a}^{${n}}\\cdot${a}^2}{${a}^3}`)}.`,correct:math(`${a}^{${n-1}}`),distractors:[math(`${a}^{${n+5}}`),math(`${a}^{${n-5}}`),math(`${a}^{${n}}`),ua(n-1)],explanation:'Під час множення степенів показники додаємо, під час ділення — віднімаємо.'});}const n=pick([2,3,4]);return makeChoice('powers_roots_transform',{topic:'powers_roots',variant:'radical-factor',question:`Спростіть ${math(`\\sqrt{${a*a*n}}`)}.`,correct:math(`${a}\\sqrt{${n}}`),distractors:[math(`${a*n}`),math(`${a*a}\\sqrt{${n}}`),math(`\\sqrt{${a*n}}`),ua(a+n)],explanation:`Виносимо повний квадрат ${a*a} з-під кореня.`});}
function workRate(){const a=pick([6,8,10,12]),b=pick([12,15,18,24]);const num=a*b,den=a+b;const t=num/den;if(!Number.isInteger(t))return workRate();return makeChoice('word_work_rate',{topic:'word_problems',variant:'joint-work',question:`Перший виконавець може виконати роботу за ${a} год, другий — за ${b} год. За скільки годин вони виконають її разом?`,correct:ua(t),distractors:[ua(a+b),ua((a+b)/2),ua(Math.abs(b-a)),ua(Math.min(a,b)/2)],explanation:`Спільна продуктивність ${math(`1/${a}+1/${b}`)} роботи за годину. Час — обернена величина: ${t} год.`,difficulty:'середній'});}
function speedContext(){const v1=pick([40,50,60,70]),v2=pick([60,70,80,90]),t=pick([2,3,4]);const dist=(v1+v2)*t;return makeChoice('word_motion',{topic:'word_problems',variant:'opposite-motion',question:`Два автомобілі одночасно виїхали з одного пункту в протилежних напрямках зі швидкостями ${v1} км/год і ${v2} км/год. Яка відстань буде між ними через ${t} год?`,correct:ua(dist),distractors:[ua(Math.abs(v2-v1)*t),ua((v1+v2)+t),ua(v1*v2*t),ua(dist/t)],explanation:`Швидкість віддалення ${v1}+${v2}=${v1+v2} км/год. За ${t} год відстань ${dist} км.`});}
function advancedChoice(){return pick([triangleCosine,circleAngle,quadraticIneq,systemLinear])();}

// --- Matching ---
function matchingFunctions(){const v=randInt(0,1);if(v===0){const m=pick([2,3]);const left=[math(`y=${m}x`),math(`y=${m}x+2`),math(`y=-${m}x+4`)];const options=['проходить через початок координат','має додатний кутовий коефіцієнт і не проходить через початок','має від’ємний кутовий коефіцієнт','є горизонтальною прямою','не перетинає вісь y'];return makeMatching('matching_functions',{topic:'functions',variant:'lines-properties',question:'До кожної функції (1–3) доберіть її властивість (А–Д).',left,options,correct_pairs:{'0':'А','1':'Б','2':'В'},explanation:'Для прямої y=kx+b знак k визначає нахил, а b — перетин з віссю y.'});}
 const left=[math('y=x^2'),math('y=x^2-3'),math('y=-x^2')];const options=['вершина в точці (0;0), гілки вгору','вершина в точці (0;−3), гілки вгору','вершина в точці (0;0), гілки вниз','графік є прямою','функція непарна'];return makeMatching('matching_functions',{topic:'functions',variant:'parabolas-properties',question:'Узгодьте функцію (1–3) з характеристикою її графіка (А–Д).',left,options,correct_pairs:{'0':'А','1':'Б','2':'В'},explanation:'Порівнюємо напрям гілок і вертикальний зсув параболи.'});}
function matchingExpressions(){const v=randInt(0,1);if(v===0){const a=pick([2,3]);const left=[math(`${a}^0`),math(`${a}^2`),math(`${a}^3`)];const vals=[1,a*a,a**3];const bounds=[[-Infinity,0],[0,2],[2,6],[6,15],[15,Infinity]];const options=['(−∞;0]','(0;2]','(2;6]','(6;15]','(15;+∞)'];const code=x=>LETTERS[bounds.findIndex(([l,r])=>x>l&&x<=r)];return makeMatching('matching_expressions',{topic:'powers_roots',variant:'powers-intervals',question:'Узгодьте вираз (1–3) з проміжком (А–Д), якому належить його значення.',left,options,correct_pairs:{'0':code(vals[0]),'1':code(vals[1]),'2':code(vals[2])},explanation:`Значення: ${vals.join(', ')}.`});}
 const left=[math('\\sqrt{16}'),math('\\log_2 8'),math('3^{-1}')];const options=['(0;1)','[1;2)','[2;3)','[3;4)','[4;+∞)'];return makeMatching('matching_expressions',{topic:'powers_roots',variant:'mixed-values',question:'Узгодьте вираз (1–3) з проміжком (А–Д), якому належить його значення.',left,options,correct_pairs:{'0':'Д','1':'Г','2':'А'},explanation:'Обчислюємо значення: 4, 3 та 1/3.'});}
function matchingPlanimetry(){const v=randInt(0,1);if(v===0){const cfg=pick([{side:5,base:6,h:4},{side:10,base:12,h:8},{side:13,base:10,h:12},{side:15,base:18,h:12}]);const {side,base,h}=cfg,area=base*h/2;const left=['Довжина основи AB','Висота трикутника до AB','Площа трикутника ABC'];const values=[base,h,area];let optionVals=unique([...values,side,base+h]);while(optionVals.length<5)optionVals.push(String(Number(optionVals.at(-1))+1));optionVals=shuffle(optionVals.slice(0,5));const code=v=>LETTERS[optionVals.indexOf(String(v))];return makeMatching('matching_planimetry',{topic:'planimetry',variant:'isosceles-triangle',question:'На рисунку зображено рівнобедрений трикутник. Узгодьте величину (1–3) з її значенням (А–Д).',left,options:optionVals.map(ua),correct_pairs:{'0':code(base),'1':code(h),'2':code(area)},explanation:`Висота ділить основу навпіл; за Піфагором h=${h}; площа ${area}.`,diagram_svg:triangleCosSvg(side,side,40,base)});}
 const top=8,bottom=20,h=8,mid=(top+bottom)/2,area=(top+bottom)*h/2;let vals=shuffle([mid,h,area,bottom-top,top+h]);const code=x=>LETTERS[vals.indexOf(x)];return makeMatching('matching_planimetry',{topic:'planimetry',variant:'trapezoid',question:'На рисунку зображено трапецію. Узгодьте величину (1–3) з її числовим значенням (А–Д).',left:['Середня лінія трапеції','Висота трапеції','Площа трапеції'],options:vals.map(ua),correct_pairs:{'0':code(mid),'1':code(h),'2':code(area)},explanation:`Середня лінія ${(top+bottom)}/2=${mid}; площа (${top}+${bottom})·${h}/2=${area}.`,diagram_svg:trapezoidSvg(top,bottom,h)});}

// --- Short answer ---
function shortCalculus(){const v=randInt(0,2);if(v===0){const a=pick([2,3,4]),u=pick([2,3]),val=a*u*u/2+2*u;return makeShort('short_calculus',{topic:'calculus',variant:'integral-linear',question:`Обчисліть ${math(`\\int_0^{${u}}(${a}x+2)\\,dx`)}.`,correct_value:val,explanation:`Первісна: ${math(`F(x)=\\frac{${a}}2x^2+2x`)}. F(${u})−F(0)=${ua(val)}.`});}
 if(v===1){const r1=pick([-4,-3,-2]),r2=pick([2,3,4]);const sum=r1+r2,prod=r1*r2;return makeShort('short_calculus',{topic:'calculus',variant:'critical-point',question:`Похідна функції має вигляд ${math(`f'(x)=3(x-${r1})(x-${r2})`)}. Визначте більшу критичну точку функції.`,correct_value:r2,explanation:`Критичні точки — нулі похідної: ${r1} і ${r2}. Більша — ${r2}.`});}
 const a=pick([1,2,3]),x0=pick([1,2,3]);const value=3*a*x0*x0-6*x0;return makeShort('short_calculus',{topic:'calculus',variant:'derivative-polynomial',question:`Для ${math(`f(x)=${a}x^3-3x^2+7`)} обчисліть ${math(`f'(${x0})`)}.`,correct_value:value,explanation:`${math(`f'(x)=${3*a}x^2-6x`)}. Підставляємо ${x0}.`});}
function shortApplied(){const v=randInt(0,2);if(v===0){const small=pick([500,600,700,800,900]),p=pick([20,25,40,50]),large=small*(1+p/100),total=small+large;return makeShort('short_applied',{topic:'word_problems',variant:'two-prices',question:`Вартість більшого замовлення на ${p}% вища за вартість меншого. Разом вони коштують ${ua(total)} грн. Визначте вартість більшого замовлення.`,correct_value:large,explanation:`Нехай менше коштує x. Тоді більше ${(1+p/100)}x, звідси знаходимо x і більшу вартість ${large}.`});}
 if(v===1){const rows=pick([12,14,16,18]),fav=3,prob=fav/rows;return makeShort('short_applied',{topic:'probability_stats',variant:'rows-probability',question:`У залі ${rows} однакових рядів, у кожному по 6 місць. Місце обирають навмання. Яка кількість рядів мала б бути, якщо ймовірність отримати місце в перших трьох рядах дорівнює ${frac(3,rows)}?`,correct_value:rows,explanation:'Частка місць у перших трьох рядах дорівнює 3/n, звідси n визначається зі заданої ймовірності.'});}
 const base=pick([800,1000,1200]),d1=pick([10,20]),d2=pick([20,25]);const total=base+base*(1-d1/100)+base*(1-d2/100);return makeShort('short_applied',{topic:'word_problems',variant:'family-discounts',question:`Три квитки коштують по ${base} грн. На другий надають знижку ${d1}%, на третій — ${d2}%. Скільки гривень потрібно заплатити разом?`,correct_value:total,explanation:'Обчислюємо дві ціни зі знижками та додаємо до повної ціни першого квитка.'});}
function shortStereo(){const v=randInt(0,1);if(v===0){const k=pick([1,2]),coneCoeff=100*k*k*k,answer=900*k*k*k;return makeShort('short_stereometry_linked_solids',{topic:'stereometry',variant:'cone-pyramid',question:`На рисунку зображено правильну трикутну піраміду та конус. Радіус основи конуса відноситься до його висоти як 5:12. Радіус конуса дорівнює радіусу кола, вписаного в основу піраміди, а висота піраміди у ${math('\\sqrt3')} раза більша за висоту конуса. Обчисліть об’єм піраміди, якщо об’єм конуса ${math(`${coneCoeff}\\pi`)} см³.`,correct_value:answer,explanation:'Через об’єм конуса визначаємо його масштаб, далі радіус вписаного кола задає сторону рівносторонньої основи піраміди. Підставляємо у формулу об’єму піраміди.',diagram_svg:cylinderPrismSvg()});}
 const r=pick([4,6,8]),h=pick([6,9,12]),vol=r*r*h;const answer=3*Math.sqrt(3)*r*r*h/4;const safe=Math.round(answer);return makeShort('short_stereometry_linked_solids',{topic:'stereometry',variant:'cylinder-prism',question:`Циліндр і правильна трикутна призма мають однакову висоту ${h}. Радіус циліндра дорівнює радіусу описаного кола навколо основи призми й дорівнює ${r}. Обчисліть об’єм призми. У відповіді округліть до цілого.`,correct_value:safe,explanation:'Для рівностороннього трикутника R=a/√3, тому a=R√3. Площа основи 3√3R²/4, об’єм — добуток на висоту.',diagram_svg:cylinderPrismSvg()});}
function shortParameter(){const v=randInt(0,1);if(v===0){let c=pick([-5,-4,-3,-2,2,3,4,5]),d=pick([-7,-6,-1,1,6,7,8]);while(d===c)d+=1;const answer=c+d,cTerm=c<0?`(x+${Math.abs(c)})`:`(x-${c})`,dTerm=d<0?`(x+${Math.abs(d)})`:`(x-${d})`;return makeShort('short_parameter_roots',{topic:'equations',variant:'rational-unique-root',question:`Визначте суму всіх значень параметра ${math('a')}, за кожного з яких рівняння ${math(`\\frac{(x-a)${cTerm}}{${dTerm}}=0`)} має єдиний розв’язок.`,correct_value:answer,explanation:`Корені чисельника: a і ${c}; ОДЗ виключає ${d}. Єдиний корінь маємо при a=${c} або a=${d}; сума ${answer}.`});}
 const p=pick([2,3,4,5]);const answer=2*p;return makeShort('short_parameter_roots',{topic:'equations',variant:'quadratic-discriminant',question:`Визначте значення параметра a, за якого рівняння ${math(`x^2-2${p}x+a=0`)} має єдиний корінь.`,correct_value:p*p,explanation:`Єдиний корінь квадратного рівняння маємо при D=0: ${(2*p)**2}-4a=0, звідси a=${p*p}.`});}

const GEN={
 data_chart_reading:dataChart,applied_ratio_percent:appliedPercent,planimetry_angle_parallel:planAngle,triangle_cosine_nmt:triangleCosine,circle_inscribed_angle:circleAngle,similar_triangles_ratio:similarTriangles,
 linear_inequality_pick:linearIneq,quadratic_inequality_interval:quadraticIneq,solid_geometry_concept:solidConcept,function_graph_transform:functionShift,probability_counting_basic:probabilityBasic,vectors_3d:vectors3d,
 algebra_simplify:algebraSimplify,geometry_statements:geometryStatements,log_exp_equation_interval:logEquation,calculus_basic:calculusBasic,circle_rectangle_geometry:circleRect,trig_exact_values:trigExact,
 advanced_single_choice:advancedChoice,quadratic_equation:quadraticChoice,systems_linear:systemLinear,progression_ap:progression,powers_roots_transform:powersRoots,word_work_rate:workRate,word_motion:speedContext,
 matching_functions:matchingFunctions,matching_expressions:matchingExpressions,matching_planimetry:matchingPlanimetry,short_calculus:shortCalculus,short_applied:shortApplied,short_stereometry_linked_solids:shortStereo,short_parameter_roots:shortParameter
};
const TRAINING_BY_TOPIC={
 numbers:['algebra_simplify','powers_roots_transform'],percents:['applied_ratio_percent'],powers_roots:['powers_roots_transform','algebra_simplify'],logarithms:['log_exp_equation_interval'],equations:['quadratic_equation','short_parameter_roots'],inequalities:['linear_inequality_pick','quadratic_inequality_interval'],systems:['systems_linear'],
 functions:['function_graph_transform','matching_functions'],progressions:['progression_ap'],trigonometry:['trig_exact_values'],calculus:['calculus_basic'],probability_stats:['data_chart_reading','probability_counting_basic'],
 planimetry:['planimetry_angle_parallel','triangle_cosine_nmt','circle_inscribed_angle','similar_triangles_ratio','geometry_statements','circle_rectangle_geometry'],
 stereometry:['solid_geometry_concept','vectors_3d'],word_problems:['applied_ratio_percent','word_work_rate','word_motion']
};
const TRAINING_ALL=Object.values(TRAINING_BY_TOPIC).flat();

export function generateByBlueprint(id){const fn=GEN[id];if(!fn)throw new Error(`Unknown blueprint ${id}`);return fn();}
function tooSimilar(candidate,avoidList=[]){const sk=candidate.question_skeleton||questionSkeleton(candidate.question);return avoidList.some(x=>questionSkeleton(typeof x==='string'?x:(x?.question||''))===sk);}
export function generateTrainingChoice(topic='mixed',difficulty='середній',avoidList=[]){const raw=topic==='mixed'?TRAINING_ALL:(TRAINING_BY_TOPIC[topic]||TRAINING_ALL);const pool=shuffle(raw);let fallback=null;for(let i=0;i<80;i++){const id=pool[i%pool.length]||pick(raw);const q=generateByBlueprint(id);if(q.type!=='choice')continue;if(!fallback)fallback=q;if(tooSimilar(q,avoidList))continue;return {...q,difficulty};}if(fallback)return {...fallback,difficulty};throw new Error('Could not produce training question');}
export function generateExamQuestions(){const usedVariants=new Set();const qs=EXAM_SLOTS.map(slot=>{let q=null;for(let i=0;i<20;i++){const id=pick(slot.blueprint_ids);const c=generateByBlueprint(id);if(c.type!==slot.type)continue;if(usedVariants.has(c.variant_key)&&slot.type==='choice')continue;q=c;break;}if(!q){const id=pick(slot.blueprint_ids);q=generateByBlueprint(id);}usedVariants.add(q.variant_key);return {...q,number:slot.slot,id:`nmt-${slot.slot}-${Date.now()}-${randInt(100,999)}`,engine_version:QUESTION_ENGINE_VERSION};});validateExamQuestions(qs);return qs;}
export function validateQuestion(q){if(!q||!q.question||!q.topic||!q.blueprint_id)return false;if(q.type==='choice')return Array.isArray(q.options)&&q.options.length===5&&new Set(q.options).size===5&&Number.isInteger(q.correct_index)&&q.correct_index>=0&&q.correct_index<5&&typeof q.explanation==='string'&&q.explanation.length>0;if(q.type==='matching')return Array.isArray(q.left)&&q.left.length===3&&Array.isArray(q.match_options)&&q.match_options.length===5&&new Set(q.match_options.map(x=>x.label)).size===5&&Object.values(q.correct_pairs||{}).length===3;if(q.type==='short')return Number.isFinite(q.correct_value);return false;}
export function validateExamQuestions(qs){if(!Array.isArray(qs)||qs.length!==22)throw new Error('Exam must contain 22 questions');if(qs.filter(q=>q.type==='choice').length!==15)throw new Error('Need 15 choice');if(qs.filter(q=>q.type==='matching').length!==3)throw new Error('Need 3 matching');if(qs.filter(q=>q.type==='short').length!==4)throw new Error('Need 4 short');if(qs.reduce((s,q)=>s+q.max_score,0)!==32)throw new Error('Need max score 32');qs.forEach((q,i)=>{if(!validateQuestion(q))throw new Error(`Invalid question ${i+1}`)});return true;}
