import { choiceFromModel, createGenome, pick, ua } from './shared.js';

function g(concept,extra={}){return createGenome({topic:'planimetry',subtopic:'Коло',family:'circles',concept,solutionPath:['identify_circle_relation','derive_angle_or_length','combine_with_secondary_relation','compute_target'],steps:4,hiddenRelations:['circle_theorem','secondary_geometry_relation'],conceptualJumps:2,algebraLoad:1,visualReasoning:4,theoremRecall:3,combinedTopics:['triangles'],context:'geometry',representation:'diagram',visualTopology:'circle_2d',parameterPattern:'angle-or-diameter-controlled',answerFormat:'choice',distractorLogic:['central_vs_inscribed','supplementary_angle','radius_vs_diameter','ignore_cyclic_relation'],wordingStyle:'nmt-geometry',...extra});}

function cyclicQuadrilateral(){const A=pick([68,72,75,80,84]);const C=180-A;const extra=pick([10,15,20]);const target=C-extra;return choiceFromModel({blueprintId:'circle_inscribed_angle',topic:'planimetry',variant:'v4-cyclic-quadrilateral-derived',question:`Чотирикутник ABCD вписано в коло. ∠A=${A}°, а ∠C на ${extra}° більший за кут x. Знайдіть x.`,correct:ua(target),distractors:[ua(C),ua(180-C),ua(A-extra),ua(180-A+extra)],explanation:`У вписаному чотирикутнику протилежні кути в сумі дають 180°: ∠C=${C}°. Тоді x=${C}−${extra}=${target}°.`,genome:g('cyclic-opposite-angles',{solutionPath:['cyclic_quadrilateral_opposite_sum','derive_opposite_angle','remove_offset']}) ,visualSpec:{type:'circle_angle',diagram_type:'circle',data:{central:2*target},labels:{}}});}

function thalesPythagoras(){const [a,b,d]=pick([[6,8,10],[9,12,15],[12,16,20],[15,20,25]]);const r=d/2;return choiceFromModel({blueprintId:'circle_inscribed_angle',topic:'planimetry',variant:'v4-thales-radius',question:`Трикутник ABC вписано в коло, причому AC — діаметр. Відомо, що AB=${a}, BC=${b}. Знайдіть радіус кола.`,correct:ua(r),distractors:[ua(d),ua((a+b)/2),ua(Math.sqrt(a*b)),ua(Math.abs(a-b)/2)],explanation:`За теоремою Фалеса ∠ABC=90°. Тому AC=√(${a}²+${b}²)=${d}. Радіус дорівнює половині діаметра: ${r}.`,genome:g('thales-plus-pythagoras',{solutionPath:['diameter_implies_right_angle','pythagorean_diameter','halve_for_radius'],hiddenRelations:['diameter_is_hypotenuse'],conceptualJumps:3}),visualSpec:{type:'circle_diameter',diagram_type:'circle',data:{diameter:d,showPoint:true},labels:{}}});}

function centralInscribedChain(){const ins=pick([25,30,35,40]);const central=2*ins;const target=180-central;return choiceFromModel({blueprintId:'circle_inscribed_angle',topic:'planimetry',variant:'v4-inscribed-central-isosceles-chain',question:`Вписаний кут, що спирається на дугу AB, дорівнює ${ins}°. O — центр кола. Знайдіть кут OAB у трикутнику AOB.`,correct:ua(target/2),distractors:[ua(ins),ua(central),ua(target),ua(90-ins)],explanation:`Центральний кут AOB, що спирається на ту саму дугу, дорівнює ${central}°. OA=OB, тому трикутник AOB рівнобедрений, а кожний кут при основі дорівнює (180°−${central}°)/2=${target/2}°.`,genome:g('inscribed-to-central-to-isosceles',{solutionPath:['double_inscribed_angle','recognize_radii_equal','base_angles_of_isosceles'],hiddenRelations:['radii_form_isosceles_triangle'],conceptualJumps:3}),visualSpec:{type:'circle_angle',diagram_type:'circle',data:{central},labels:{}}});}

function rectangleInCircle(){const [w,h,d]=pick([[6,8,10],[8,15,17],[10,24,26],[12,16,20]]);const areaCircle=Math.PI*(d/2)**2;const coeff=d*d/4;return choiceFromModel({blueprintId:'circle_rectangle_geometry',topic:'planimetry',variant:'v4-rectangle-diagonal-circle-area',question:`Прямокутник зі сторонами ${w} і ${h} вписано в коло. Знайдіть площу кола у вигляді kπ. Чому дорівнює k?`,correct:ua(coeff),distractors:[ua(d),ua(d*d),ua(w*h),ua((w+h)/2)],explanation:`Діагональ прямокутника є діаметром кола: d=√(${w}²+${h}²)=${d}. Радіус r=${d/2}, тому S=πr²=${coeff}π. Отже k=${coeff}.`,genome:g('rectangle-diagonal-as-diameter',{solutionPath:['rectangle_diagonal_pythagoras','diagonal_is_circle_diameter','radius_half_diameter','area_coefficient'],hiddenRelations:['rectangle_diagonal_equals_diameter'],conceptualJumps:3}),visualSpec:{type:'circle_rectangle',diagram_type:'circle_rectangle',data:{width:w,height:h},labels:{}},preferredRenderer:'tikz'});}

export function generateCircleV4(blueprintId='circle_inscribed_angle'){
  if(blueprintId==='circle_rectangle_geometry') return rectangleInCircle();
  return pick([cyclicQuadrilateral,thalesPythagoras,centralInscribedChain])();
}
