import { choiceFromModel, createGenome, pick, ri, ua, math } from './shared.js';

function g(concept,extra={}){return createGenome({topic:'functions',subtopic:'Функції та графіки',family:'functions',concept,solutionPath:['interpret_representation','identify_invariant','perform_transform','read_target'],steps:4,hiddenRelations:['graph_parameter_relation'],conceptualJumps:2,algebraLoad:2,visualReasoning:3,theoremRecall:1,combinedTopics:['coordinate_geometry'],context:'abstract',representation:'graph',visualTopology:'coordinate_function_graph',parameterPattern:'small-integers',answerFormat:'choice',distractorLogic:['wrong_shift_direction','wrong_axis','vertex_vs_intercept','slope_sign'],wordingStyle:'nmt-graph',...extra});}

function transformedParabola(){const h=pick([-3,-2,1,2,3]),k=pick([-4,-3,-2,2,3]);const x0=h+pick([1,2]);const y=(x0-h)**2+k;return choiceFromModel({blueprintId:'function_graph_transform',topic:'functions',variant:'v4-parabola-read-transform',question:`На рисунку подано графік функції ${math(`y=(x-${h})^2${k>=0?'+':''}${k}`)}. Якого значення набуває функція при x=${x0}?`,correct:ua(y),distractors:[ua((x0+h)**2+k),ua((x0-h)**2-k),ua(h),ua(k)],explanation:`Підставляємо x=${x0}: y=(${x0}−${h})²${k>=0?'+':''}${k}=${y}.`,genome:g('parabola-evaluate-after-transform'),visualSpec:{type:'function_graph',diagram_type:'graph',data:{kind:'parabola',h,k,xMin:-5,xMax:5},labels:{}}});}

function lineIntersection(){const m1=pick([2,3]),m2=pick([-2,-1]);const x=pick([1,2,3]);const b1=pick([-3,-1,1,2]);const y=m1*x+b1;const b2=y-m2*x;return choiceFromModel({blueprintId:'function_graph_transform',topic:'functions',variant:'v4-two-lines-intersection-x',question:`Прямі ${math(`y=${m1}x${b1>=0?'+':''}${b1}`)} і ${math(`y=${m2}x${b2>=0?'+':''}${b2}`)} перетинаються в точці A. Знайдіть абсцису точки A.`,correct:ua(x),distractors:[ua(y),ua(b2-b1),ua(-x),ua(x+1)],explanation:`У точці перетину значення y однакові: ${m1}x${b1>=0?'+':''}${b1}=${m2}x${b2>=0?'+':''}${b2}. Звідси x=${x}.`,genome:g('intersection-of-two-lines',{solutionPath:['equate_function_values','solve_linear_equation','identify_abscissa'],algebraLoad:3}),visualSpec:{type:'function_graph',diagram_type:'graph',data:{kind:'line',slope:m1,intercept:b1,xMin:-5,xMax:5},labels:{}}});}

function vertexDistance(){const h=pick([-4,-3,-2,2,3,4]);const k=pick([-4,-3,-2,2,3,4]);const dist2=h*h+k*k;return choiceFromModel({blueprintId:'function_graph_transform',topic:'functions',variant:'v4-vertex-distance-squared',question:`Вершина параболи ${math(`y=(x-${h})^2${k>=0?'+':''}${k}`)} — точка M. Знайдіть квадрат відстані від M до початку координат.`,correct:ua(dist2),distractors:[ua(Math.abs(h)+Math.abs(k)),ua((h-k)**2),ua(h+k),ua(Math.abs(h*k))],explanation:`Вершина має координати M(${h}; ${k}). Квадрат відстані до O(0;0): OM²=${h}²+${k}²=${dist2}.`,genome:g('vertex-coordinate-to-distance',{combinedTopics:['coordinate_geometry','distance_formula'],hiddenRelations:['vertex_coordinates_must_be_read_from_canonical_form'],conceptualJumps:3}),visualSpec:{type:'function_graph',diagram_type:'graph',data:{kind:'parabola',h,k,xMin:-5,xMax:5},labels:{}}});}

function compositionLinear(){const a=pick([2,3,4]),b=pick([-3,-2,1,2]),c=pick([2,3]),d=pick([-2,-1,1,3]),x=pick([1,2,3]);const gx=c*x+d;const ans=a*gx+b;return choiceFromModel({blueprintId:'function_graph_transform',topic:'functions',variant:'v4-function-composition-linear',question:`Функції задано формулами ${math(`f(x)=${a}x${b>=0?'+':''}${b}`)} і ${math(`g(x)=${c}x${d>=0?'+':''}${d}`)}. Знайдіть f(g(${x})).`,correct:ua(ans),distractors:[ua(a*x+b+c*x+d),ua(c*(a*x+b)+d),ua(a*x+b),ua(gx)],explanation:`Спочатку g(${x})=${gx}. Потім f(${gx})=${a}·${gx}${b>=0?'+':''}${b}=${ans}.`,genome:g('function-composition',{representation:'formula',visualTopology:null,visualReasoning:0,hiddenRelations:['order_of_composition'],combinedTopics:['algebraic_substitution']})});}

const variants=[transformedParabola,lineIntersection,vertexDistance,compositionLinear];
export function generateFunctionsV4(){return pick(variants)();}
