import { choiceFromModel, shortFromModel, createGenome, pick, ri, ua, math } from './shared.js';

function g(concept, extra={}){return createGenome({topic:'equations',subtopic:'Квадратні рівняння',family:'quadratic',concept,solutionPath:['extract_structure','apply_vieta_or_discriminant','transform_target','verify'],steps:4,hiddenRelations:['roots_relation','target_not_direct_root'],conceptualJumps:2,algebraLoad:3,theoremRecall:2,combinedTopics:['algebraic_expressions'],context:'abstract',representation:'formula',parameterPattern:'integer-roots-controlled',answerFormat:'choice',distractorLogic:['sign_vieta','sum_vs_product','forget_transform','discriminant_error'],wordingStyle:'nmt-compact',...extra});}

function transformedRoots(requiredType){const r1=pick([-5,-4,-3,-2,1,2]);const r2=pick([3,4,5,6]);if(r1===r2)return transformedRoots(requiredType);const b=-(r1+r2),c=r1*r2;const target=(r1+1)*(r2+1);const q=`Корені x₁ і x₂ рівняння ${math(`x^2${b>=0?'+':''}${b}x${c>=0?'+':''}${c}=0`)}. Знайдіть значення виразу ${math(`(x_1+1)(x_2+1)`)}.`;const genome=g('transformed-roots-product',{solutionPath:['vieta_sum_product','expand_transformed_product','substitute_symmetric_values']});if(requiredType==='short')return shortFromModel({blueprintId:'quadratic_equation',topic:'equations',variant:'v4-transformed-roots-short',question:q,correctValue:target,explanation:`(x₁+1)(x₂+1)=x₁x₂+(x₁+x₂)+1=${c}+${r1+r2}+1=${target}.`,genome:{...genome,answer_format:'short'}});return choiceFromModel({blueprintId:'quadratic_equation',topic:'equations',variant:'v4-transformed-roots',question:q,correct:ua(target),distractors:[ua(c+1),ua(r1+r2+1),ua(c-(r1+r2)+1),ua((r1+r2)*c)],explanation:`За Вієтом x₁+x₂=${r1+r2}, x₁x₂=${c}. Розкриваємо добуток і отримуємо ${target}.`,genome});}

function parameterRepeatedRoot(){const m=pick([2,3,4,5,6]);const p=2*m;const q=m*m;const shift=pick([1,2,3]);const ans=p+shift;return choiceFromModel({blueprintId:'quadratic_equation',topic:'equations',variant:'v4-parameter-discriminant-zero',question:`Для якого значення a рівняння ${math(`x^2-(a-${shift})x+${q}=0`)} має єдиний корінь?`,correct:ua(ans),distractors:[ua(p-shift),ua(q+shift),ua(m+shift),ua(2*q+shift)],explanation:`Єдиний корінь маємо при D=0: (a−${shift})²−4·${q}=0. Для додатного коефіцієнта суми коренів a−${shift}=${p}, отже a=${ans}.`,genome:g('parameter-double-root',{hiddenRelations:['single_root_means_discriminant_zero','coefficient_encodes_parameter'],conceptualJumps:3})});}

function reciprocalRoots(){const r1=pick([2,3,4]);const r2=pick([5,6,8]);const s=r1+r2,p=r1*r2;const target=s/p;return choiceFromModel({blueprintId:'quadratic_equation',topic:'equations',variant:'v4-reciprocal-roots',question:`Нехай x₁ і x₂ — корені рівняння ${math(`x^2-${s}x+${p}=0`)}. Знайдіть ${math(`\\frac1{x_1}+\\frac1{x_2}`)}.`,correct:ua(target),distractors:[ua(s),ua(p/s),ua(1/s),ua(1/p)],explanation:`1/x₁+1/x₂=(x₁+x₂)/(x₁x₂). За Вієтом це ${s}/${p}=${ua(target)}.`,genome:g('reciprocal-roots',{solutionPath:['vieta','combine_reciprocals','substitute_symmetric_values'],hiddenRelations:['common_denominator_is_root_product']})});}

function shiftedEquation(){const r1=pick([-3,-2,1,2]);const r2=pick([4,5,6]);const k=pick([2,3]);const y1=r1+k,y2=r2+k;const s=y1+y2,p=y1*y2;const target=r1*r2;return choiceFromModel({blueprintId:'quadratic_equation',topic:'equations',variant:'v4-shifted-variable-roots',question:`Числа x₁ і x₂ задовольняють рівняння ${math(`(x+${k})^2-${s}(x+${k})+${p}=0`)}. Знайдіть x₁x₂.`,correct:ua(target),distractors:[ua(p),ua(y1+y2),ua((r1+r2)),ua(p-k*k)],explanation:`Позначимо y=x+${k}. Тоді корені рівняння за y: ${y1} і ${y2}. Отже x₁=${r1}, x₂=${r2}, тому x₁x₂=${target}.`,genome:g('shifted-variable',{hiddenRelations:['substitution_required','roots_belong_to_shifted_variable'],conceptualJumps:3,algebraLoad:4})});}

const variants=[transformedRoots,parameterRepeatedRoot,reciprocalRoots,shiftedEquation];
export function generateQuadraticV4(requiredType=null){return pick(variants)(requiredType);}
