import { choiceFromModel, createGenome, pick, ua } from './shared.js';

function g(concept,extra={}){return createGenome({topic:'planimetry',subtopic:'Трикутники',family:'triangles',concept,solutionPath:['extract_geometry','choose_theorem','derive_intermediate','compute_target'],steps:4,hiddenRelations:['auxiliary_relation','target_not_directly_given'],conceptualJumps:2,algebraLoad:2,visualReasoning:3,theoremRecall:3,combinedTopics:['algebra'],context:'geometry',representation:'diagram',visualTopology:'triangle_2d',parameterPattern:'controlled-exact',answerFormat:'choice',distractorLogic:['wrong_theorem','missing_square','wrong_angle_relation','use_given_not_derived'],wordingStyle:'nmt-geometry',...extra});}

function cosineThenPerimeter(){const [a,b]=pick([[5,8],[6,6],[7,7],[8,8],[10,10]]),angle=60;const c2=a*a+b*b-a*b,c=Math.sqrt(c2),per=a+b+c;return choiceFromModel({blueprintId:'triangle_cosine_nmt',topic:'planimetry',variant:'v4-cosine-then-perimeter',question:`У трикутнику ABC відомо AB=${a}, AC=${b}, ∠A=${angle}°. Знайдіть периметр трикутника.`,correct:ua(per),distractors:[ua(a+b+Math.sqrt(a*a+b*b)),ua(a+b),ua(c2),ua(a+b+Math.abs(a-b))],explanation:`За теоремою косинусів BC²=${a}²+${b}²−2·${a}·${b}·cos60°=${c2}, тому BC=${ua(c)}. Периметр дорівнює ${ua(per)}.`,genome:g('cosine-law-derived-side-then-perimeter'),visualSpec:{type:'triangle_sides',diagram_type:'triangle',data:{left:b,right:ua(c),base:a,angle},labels:{}}});}
function rightAltitude(){const [a,b,c]=pick([[6,8,10],[9,12,15],[12,16,20],[15,20,25]]);const h=a*b/c;return choiceFromModel({blueprintId:'triangle_cosine_nmt',topic:'planimetry',variant:'v4-right-triangle-altitude',question:`Катети прямокутного трикутника дорівнюють ${a} і ${b}. Знайдіть висоту, проведену з вершини прямого кута до гіпотенузи.`,correct:ua(h),distractors:[ua(c),ua((a+b)/2),ua(a*b/(a+b)),ua(Math.abs(a-b))],explanation:`Гіпотенуза c=${c}. Із рівності площ ab/2=ch/2 маємо h=ab/c=${ua(h)}.`,genome:g('right-triangle-altitude-via-area',{solutionPath:['pythagorean_hypotenuse','equate_two_area_formulas','solve_altitude'],hiddenRelations:['same_area_two_formulas'],conceptualJumps:3}),visualSpec:{type:'right_triangle',diagram_type:'triangle',data:{a,b,c,showAltitude:true},labels:{}}});}
function angleBisectorRatio(){const [ratioA,ratioB,bd]=pick([[2,3,4],[2,5,6],[3,4,6],[3,5,6]]);const dc=bd*ratioB/ratioA,bc=bd+dc;return choiceFromModel({blueprintId:'triangle_cosine_nmt',topic:'planimetry',variant:'v4-angle-bisector-segment',question:`У трикутнику ABC бісектриса AD ділить сторону BC на відрізки BD і DC. Відомо, що AB:AC=${ratioA}:${ratioB}, а BD=${bd}. Знайдіть BC.`,correct:ua(bc),distractors:[ua(dc),ua(bd*ratioA/ratioB+bd),ua(bd*(ratioA+ratioB)),ua(bd+ratioB)],explanation:`За теоремою про бісектрису BD:DC=AB:AC=${ratioA}:${ratioB}. Тому DC=${ua(dc)}, а BC=${ua(bc)}.`,genome:g('angle-bisector-ratio',{solutionPath:['recognize_angle_bisector_theorem','set_proportion','derive_second_segment','sum_side'],theoremRecall:4}),visualSpec:{type:'triangle_sides',diagram_type:'triangle',data:{left:ratioA,right:ratioB,base:ua(bc),angle:null},labels:{}}});}
function medianApollonius(){const k=pick([1,2,3,4]),a=5*k,b=5*k,c=6*k,m=4*k;return choiceFromModel({blueprintId:'triangle_cosine_nmt',topic:'planimetry',variant:'v4-median-apollonius',question:`Сторони трикутника дорівнюють ${a}, ${b} і ${c}. Знайдіть медіану, проведену до сторони довжини ${c}.`,correct:ua(m),distractors:[ua(c/2),ua((a+b)/2),ua(Math.sqrt(a*a+b*b-c*c)),ua(Math.abs(a-b)+k)],explanation:`За формулою медіани m²=(2a²+2b²−c²)/4. Після підстановки отримуємо m=${m}.`,genome:g('median-apollonius',{theoremRecall:4,hiddenRelations:['target_requires_nonbasic_triangle_formula'],conceptualJumps:2}),visualSpec:{type:'triangle_sides',diagram_type:'triangle',data:{left:a,right:b,base:c},labels:{}}});}
const variants=[cosineThenPerimeter,rightAltitude,angleBisectorRatio,medianApollonius];
export function generateTrianglesV4(){return pick(variants)();}
