import fs from 'node:fs';
import path from 'node:path';
import { validateQuestionBank } from '../factory/bank-validator.js';
import { DEFAULT_RUNTIME_BANK_PATH } from './constants.js';
import { QUESTION_ENGINE_VERSION } from '../generation/question-generator.js';
import { VISUAL_ENGINE_VERSION } from '../visuals/visual-spec.js';

export function resolveRuntimeBankPath({ root = process.cwd(), bankPath = null } = {}) {
  const requested = bankPath || process.env.NMT_OFFLINE_BANK_PATH || DEFAULT_RUNTIME_BANK_PATH;
  return path.isAbsolute(requested) ? requested : path.resolve(root, requested);
}

export function loadRuntimeBank({ root = process.cwd(), bankPath = null } = {}) {
  const absolutePath = resolveRuntimeBankPath({ root, bankPath });
  if (!fs.existsSync(absolutePath)) {
    throw new Error(`Offline NMT bank not found: ${absolutePath}`);
  }

  let bank;
  try {
    bank = JSON.parse(fs.readFileSync(absolutePath, 'utf8'));
  } catch (err) {
    throw new Error(`Offline NMT bank is not valid JSON: ${err.message}`);
  }

  const validation = validateQuestionBank(bank);
  if (!validation.ok) {
    throw new Error(`Offline NMT bank failed validation: ${validation.errors.slice(0, 8).join(', ')}`);
  }

  // Never silently serve a bank generated by the retired engine. This was the
  // source of the previous "deployed but nothing changed" failure mode.
  if (Number(bank.core_engine_version) !== Number(QUESTION_ENGINE_VERSION)) {
    throw new Error(`Offline NMT bank core version mismatch: bank=${bank.core_engine_version ?? 'missing'}, runtime=${QUESTION_ENGINE_VERSION}`);
  }
  if (Number(bank.visual_engine_version) !== Number(VISUAL_ENGINE_VERSION)) {
    throw new Error(`Offline NMT bank visual version mismatch: bank=${bank.visual_engine_version ?? 'missing'}, runtime=${VISUAL_ENGINE_VERSION}`);
  }

  return {
    bank,
    path: absolutePath,
    itemCount: bank.items.length,
  };
}
